### ISSUE TITLE
Clanwar scoreboard issue

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#103]
http://actionfps.com/clanwar/?id=2016-01-02T14%3A14%3A22Z

* As you can see I am missing in the "summary" (Fra|Lucas) even though i played 2 games
apparently it is only showing the players of the last game when it should show all the participants of the clanwar
* Also Million stats only count the last game he played in this clanwar
* Games aren't showing up in the right order (should be ASC startTime)

**Comment by ScalaWilliam** [comment]
Fixed by 7d8aebacd3c054c9d8f8c894e4190378e6072c4a
