### ISSUE TITLE
Same achievement showing several times on same game card

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#106]
http://actionfps.com/game/?id=2016-01-03T16:32:08Z

Hint ? shows 4 times, and zangetsu score 4 flags this game

**Comment by ScalaWilliam** [comment]
Screenshot? I can only see 1 copy

**Comment by lucasgautheron** [comment]
Check again. Now it shows 3 times
Same issue on http://actionfps.com/game/?id=2016-01-03T17:36:14Z

**Comment by lucasgautheron** [comment]
http://actionfps.com/game/?id=2016-01-03T17:15:58Z

**Comment by ScalaWilliam** [comment]
can you confirm it's ok @lucasgautheron

**Comment by lucasgautheron** [comment]
Yes

**Comment by lucasgautheron** [comment]
NVM, its back http://actionfps.com/game/?id=2016-01-03T17:36:14Z

**Comment by ScalaWilliam** [comment]
Fixed.
