### ISSUE TITLE
Clans skins

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#114]
AC allows to set custom skins for players matching a certain pattern : these skins could be available from the website on each clan page.

Could also be retrieved automatically by the client when a clan is present on the server.

**Comment by ScalaWilliam** [comment]
What's the format? Is this important? Can we just include it in the CSV?

**Comment by lucasgautheron** [comment]
I'll talk to daylixx, its one or a few JPEGs basically. low priority stuff, but thats cool, so i want it written somewhere

**Comment by ScalaWilliam** [comment]
So could be a link to a ZIP archive hosted on Dropbox or something

**Comment by lucasgautheron** [comment]
yes

**Comment by ScalaWilliam** [comment]
I moved this issue to https://github.com/ScalaWilliam/ActionFPS/wiki/Centralisation
