### ISSUE TITLE
Download button in menu

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#115]
And on page big red button. Version,  Windows icon. No need for changelog.

Maybe install instructions. Or video. Or screen shot. "How to get started"

**Comment by Paul255** [comment]
So you just want a pretty download page right ?
With install instructions ?

**Comment by ScalaWilliam** [comment]
Yeah. Whatever works. Now it's bland and boring, not interactive. 

Any kind of instruction, "1, 2, 3", whatever, just has to be something you want to do.

**Comment by lucasgautheron** [comment]
![example](https://cloud.githubusercontent.com/assets/5359646/12209384/bded6586-b652-11e5-8084-bae796f5143a.jpg)

**Comment by ScalaWilliam** [comment]
that is nice but I haven't heard of Windows 1.0.0

**Comment by lucasgautheron** [comment]
Really you haven't ? Noob :D Have a look at my edit though :D
