### ISSUE TITLE
Clan achievements

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#118]

**Comment by lucasgautheron** [comment]
* MVP count
 
From Sanzo : 
Clan achievment: winstreak 2,5,10
Need a name: play against 5,10,15 differents clans
Need a name : play x différent maps un clanwars
Clean sheet: win à clanwar without the enemy scoring à flag
Close call: win à clanwar with 1 flag diff
Reverse sweep: come back from à 1-0 déficit
I.e lose firdt game win two next
So win 2-1 when u were 1 down

**Comment by lucasgautheron** [comment]
Also add # of clanwar MVPs to player achievements ?

**Comment by ScalaWilliam** [comment]
Sounds like a separate ticket :D this changes the one-way data flow btw xD

**Comment by ScalaWilliam** [comment]
@Paul255 @pitchalo interested? ;-)

**Comment by ScalaWilliam** [comment]
@Sanzouille @lucasgautheron how important? Eg vs tournaments.

**Comment by ScalaWilliam** [comment]
Will close if no response within 2 days.
