### ISSUE TITLE
DSA Key-pair generation

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#120]
Generate key-pairs for users. Store public, use actionfps://... link (just like before) to let the game store the private key and the user id.

**Comment by Paul255** [comment]
You can check it https://gist.github.com/Paul255/6c4dec4f13ef03f6579f

**Comment by lucasgautheron** [comment]
Thanks :+1:

https://gist.github.com/Paul255/6c4dec4f13ef03f6579f#file-key-php-L38
actionfps.com:// -> actionfps://

You can also make the script that push the database to our servers.

**Comment by Paul255** [comment]
Updated
I'll make the script

**Comment by Paul255** [comment]
I need some infos : 
Where can I get the list of AF servers 
Will the login/password be the same for every servers ?
Where is stored the file on the "master server"

Thanks

**Comment by ScalaWilliam** [comment]
Closing, no progress made. Will reopen as needed.
