### ISSUE TITLE
IRC Bot to broadcast inters (!inter)

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#121]
http://actionfps.com/inters/ = Server Sent Events 
Can easily do it in python using ScalaWilliam  code bits + ircbot
```
from sseclient import SSEClient

while True:
	print("New connection")
	messages = SSEClient('http://actionfps.com/inters/')
	for message in messages:
		// do stuff with 'message'
```

BTW i guess me or @ScalaWilliam won't be doing it so thats a good thing to do for anyone else able to code and willing to contribute (@Paul255 ?)

### Channels suggested : 
 * woop-clan@gamesurge
 * assaultcube@quakenet

**Comment by Paul255** [comment]
@Sanzouille Is suggesting a teamspeak bot ? Which I think will be 50x more usefull than an IRC bot :)

**Comment by lucasgautheron** [comment]
Yes sounds great but users usually find TS messages annoying. The IRC thing is left to anyone who might want to do it, because i've been asked several times about it. I agree that IRC = the past, so don't feel obliged to do /that/, as i don't want to do it myself for this reason. Go for a TS bot then ;)

**Comment by lucasgautheron** [comment]
Done
https://gist.github.com/lucasgautheron/4bc80134aeedf5bf44e0
