### ISSUE TITLE
Registration process improvements

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#128]
Apparently (user feedback) the current registration process leads to several difficulties. Most commonly asked questions are : 
 *  "Where do i register ?". I assume this is because the user needs to click "login" (there's no "register" or "signup" link) and then he is prompted for his G+ account without further explanations.
 *  "I filled the form but it doesn't work.". Mostly because the user id specified is incorrect (e.g. it contains forbidden characters).

I suggest the following changes : 

* On the login page, create a "login" section and a "register" (first login) section. Mention briefly that G+ is required.
* user id should be the last field of the form. A default value should be suggested (basically the user name, stripped of invalid chars, and appended some value if already taken), and continuously updated as long as the user is typing is name and the ID field hasn't been manually modified

**Comment by ScalaWilliam** [comment]
Done and done! :feelsgood: :rage2: :wind_chime:
