### ISSUE TITLE
Ensure all external resources are HTTPS/secure

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#129]
So that the HTTPS site comes up with a green padlock.
https://actionfps.com/

**Comment by lucasgautheron** [comment]
https://github.com/ScalaWilliam/ActionFPS/blob/master/web/dist/www/template.html#L11 > can safely be switched to https (i checked)
what else ?

 *  map backgrounds (need to be moved to github CDN)
 *  clanwar backound (need to be moved to github CDN)
 * rvsf/cla images

**Comment by ScalaWilliam** [comment]
Yep - just refresh the page until you get a green padlock basically :)

**Comment by ScalaWilliam** [comment]
We might not be able to embed Twitch/YouTube stuff nicely because of HTTPS though, potentially. But linking to it is fine.

**Comment by lucasgautheron** [comment]
Twitch allows to embed the stream via https ( https://www-cdn.jtvnw.net/swflibs/TwitchPlayer.swf?channel=... )

**Comment by ScalaWilliam** [comment]
:+1:
