### ISSUE TITLE
http -> https

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#130]
Every resource should be accessed from secured connections

https://github.com/ScalaWilliam/ActionFPS/blob/master/web/dist/www/template.html#L11 > can safely be switched to https (i checked)
what else ?

 * map backgrounds (need to be moved to github CDN)
 * clanwar backound (need to be moved to github CDN)

**Comment by ScalaWilliam** [comment]
Yep

And rvsf.png and cla.png stuff

**Comment by lucasgautheron** [comment]
Duplicated
