### ISSUE TITLE
Create teamspeak channels for each clan

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#140]
Can be automatized.

**Comment by Paul255** [comment]
Public/Private channel for each clan + Team logo in the description
The script can be run each time a clan is added
![clanschannels](https://cloud.githubusercontent.com/assets/7859727/12894922/17eedcb8-ce9a-11e5-841e-12e47816aab8.png)

https://github.com/Paul255/actionfps_ts3bot/blob/master/ts3channel.py

**Comment by Paul255** [comment]
![channelsok](https://cloud.githubusercontent.com/assets/7859727/12896782/339d0124-cea4-11e5-9a85-47758e788b4a.png)

Done !

**Comment by lucasgautheron** [comment]
http://vignette3.wikia.nocookie.net/dragonage/images/2/2a/Anchorman-well-that-escalated-quickly.jpg/revision/latest?cb=20120921164818
