### ISSUE TITLE
Leaving during intermission

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#148]

**Comment by ScalaWilliam** [comment]
Not been raised too many times, I'm gonna close it if you don't mind @Sanzouille

**Comment by Sanzouille** [comment]
This is still a problem. but the solution comes with the new client.

**Comment by ScalaWilliam** [comment]
What do you propose to do with the ticket?

Again I'll close within 2 days if no response :-)
