### ISSUE TITLE
Contact form(s) for various functions

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#155]
I think it makes sense to have a public entry point for communicating with us that's now obvious.

Use Google Forms. Want to have the following capabilities:
* Ask for user ID & e-mail
* Nickname change requests. Include starting date and end date for a nickname.
* Reports
* Feedback and questions
* Anything else?

**Comment by ScalaWilliam** [comment]
@Sanzouille can you do something about this or I'll close it

**Comment by ScalaWilliam** [comment]
Will close within 2 days.

**Comment by Sanzouille** [comment]
We have a dev channel on discord, for this purpose. easily accessible.

**Comment by ScalaWilliam** [comment]
Closing in favour of #183
