### ISSUE TITLE
Add screenshots of the game

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#185]
So people would know what the game is about.

1. Add link to '/screenshots/' here: https://github.com/ScalaWilliam/ActionFPS/blob/master/web/dist/www/template.html
2. Add a 'sceenshots.html' file here with some screenshots:
https://github.com/ScalaWilliam/ActionFPS/tree/master/web/dist/www

**Comment by ScalaWilliam** [comment]
1. Add link to '/screenshots/' here: https://github.com/ScalaWilliam/ActionFPS/blob/master/web/dist/www/template.html
2. Add a 'sceenshots.html' file here with some screenshots:
https://github.com/ScalaWilliam/ActionFPS/tree/master/web/dist/www

**Comment by ScalaWilliam** [comment]
You can just paste the image into a github issue and then use that <img> tag in the .html page. Don't put images into the git repository.

**Comment by ScalaWilliam** [comment]
Alternatively can use Flickr and embed an iframe or something. I don't care so much.

**Comment by ScalaWilliam** [comment]
**Or you can just paste them right here. Just need some GOOD screenshots.**

**Comment by ScalaWilliam** [comment]
#188

**Comment by DnC-f0r3v3r** [comment]
1
![noscopelook](https://cloud.githubusercontent.com/assets/17777999/21547980/5afb6360-cdb7-11e6-9fda-d6c914be3fb8.png)
![noscopelook_480](https://cloud.githubusercontent.com/assets/17777999/21547981/5afdfd8c-cdb7-11e6-905c-1a376198c14c.png)


2
![nadelook](https://cloud.githubusercontent.com/assets/17777999/21547975/5aef96e8-cdb7-11e6-828c-79cc0f3e2013.png)
![nadelook_480](https://cloud.githubusercontent.com/assets/17777999/21547976/5af00966-cdb7-11e6-9a40-f450bf0dc106.png)

3
![scopelook](https://cloud.githubusercontent.com/assets/17777999/21547983/5aff0754-cdb7-11e6-9bbe-06e8707668b5.png)
![scopelook_480](https://cloud.githubusercontent.com/assets/17777999/21547984/5aff662c-cdb7-11e6-925b-78a0c66c6d4a.png)

4
![faillook](https://cloud.githubusercontent.com/assets/17777999/21547977/5af00e52-cdb7-11e6-9acc-830028d778d0.png)
![faillook_480](https://cloud.githubusercontent.com/assets/17777999/21547974/5aedf19e-cdb7-11e6-8daf-b3ba5522ec6e.png)

5
![jumpscore](https://cloud.githubusercontent.com/assets/17777999/21547978/5af048cc-cdb7-11e6-9751-0d6a7e3b82e7.png)
![jumpscore_480](https://cloud.githubusercontent.com/assets/17777999/21547973/5aed9122-cdb7-11e6-89ef-4562c7835694.png)

6
![noscopelook2](https://cloud.githubusercontent.com/assets/17777999/21547979/5afa7540-cdb7-11e6-9645-4b21e948911e.png)
![noscopelook2_480](https://cloud.githubusercontent.com/assets/17777999/21547982/5afe881a-cdb7-11e6-8ae6-e6e7cd29d638.png)
