### ISSUE TITLE
New working chat

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#19]
Could perhaps base it on Firechat?

https://www.firebase.com/tutorial/#session/uya25taneu9

**Comment by ScalaWilliam** [comment]
Or maybe just remove the current one & focus on more important things.

**Comment by lucasgautheron** [comment]
As long as the website does not offer another way for people to organize / find matches the chat has an important interest. However there are indeed more important things to work on before that.

**Comment by ScalaWilliam** [comment]
Can we organise some kind of public room for this then? A simple link to TS or something would do the trick.

I don't have the time to do a lot of research. Maybe there is a nice integrated solution like Google Hangouts that we can either link to or embed into the site. @Sanzouille might have the time? Not sure.

**Comment by Sanzouille** [comment]
If we are not doing the inter finding thingy, chat is useless for now. Focus on more important things, then we will find something when the time comes.
I'll do some research to see if something already working would fit our needs

**Comment by Sanzouille** [comment]
However @ScalaWilliam, at the moment we are not hosting any TS. I shut it down when it was getting targeted by cunts. When we move forward i'll make sure to have one started with the actionfps name.

We are currently hosting only 4 normal servers and 1 match client modded server. Thats the only thing that would need to be put on the server page

**Comment by ScalaWilliam** [comment]
Sounds good to me. We don't have to use TS by the way, could use some hosted solution. Please take a look at "WebRTC" and see if there are any solutions out there for HTML5 or so. We could have integrated communications inside the browser!

**Comment by ScalaWilliam** [comment]
for audio/video comms http://thanpol.as/webrtc/The-Cost-of-WebRTC-Today/

**Comment by ScalaWilliam** [comment]
But yes just need time. ALl this stuff is very interesting & exciting to me, wish I had all the time in the world though xD

**Comment by ScalaWilliam** [comment]
Don't need it for now.
