### ISSUE TITLE
Send Inter announcements to the Discord channel

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#200]
An 'inter' is an invitation or announcement by a player who wants to organise a new game. When a registered user types '!inter' on a server, users get a notification in a TeamSpeak channel and also an HTML5 notification if they are currently on the website.

From EventSource endpoint: `https://actionfps.com/inters/`
To Discord channel `#inters` here: https://discord.gg/YB35KE3

How this works in JavaScript on the website:
https://actionfps.com/assets/push/push.js

Detail: 
https://discordapp.com/developers/docs/intro

This is probably doable in a Node.js app :-):
https://github.com/hydrabolt/discord.js/
https://github.com/aslakhellesoy/eventsource

Please put the code in the `inter-discord` directory.

Sample payload:
```json
{"playerName": "w00p|Drakas", "serverName": "aura 1999", "serverConnect": "aura.woop.ac:1999"}
```

Expected output in the channel:
![screen shot 2016-12-31 at 20 08 30](https://cloud.githubusercontent.com/assets/2464813/21577423/edc08a98-cf94-11e6-8aa2-53713946c27f.png)

```
w00p|Drakas called an inter on 'aura 1999'. Connect: assaultcube://aura.woop.ac:1999
```

Checklist for **Node.js**:
* [x] Receive `EventSource` events and parse the JSON.
* [x] Send a message to Discord channel.
* [ ] Connect the receiver to the publisher.
* [ ] Make sure the code packages itself and is nicely deployable.
* [ ] Make sure you handle failure (disconnection from EventSource endpoint)
* [ ] Document how to use it.

Alternatively, you can do it in Scala and will be able to avoid the EventSource bits.
Checklist for **Scala**:
* [ ] Create a `services.DiscordService` class in the `web` package.
* [ ] Connect to the inter source `IntersService.intersSource`
* [ ] Determine what connector to use for Discord API.
* [ ] Make a call to Discord API to publish the message.
* [ ] Make sure to add an application shutdown hook.
You'd use `akka-streams` for this.

Node.js already comes with some nice libraries for doing this sort of thing and should be easy to get done. Scala however would run inside the web service, meaning fewer moving parts.

My preference is always Scala but Node.js will be fine too as this service can run independently from the main code anyway.

**Comment by Paul255** [comment]
It looks like this for the moment 
![image](https://cloud.githubusercontent.com/assets/7859727/21782604/43455432-d6b4-11e6-8a3d-ea99f8a17eec.png)

**Comment by ScalaWilliam** [comment]
https://github.com/Paul255/ActionFPS-Bots/tree/master/actionfps_discord

**Comment by ScalaWilliam** [comment]
@Paul255 if done please close :-)

**Comment by ScalaWilliam** [comment]
Is this completed @Paul255 ? If so, please close.

**Comment by ScalaWilliam** [comment]
& attach a final URL to da codes ;)

**Comment by Paul255** [comment]
Code here https://github.com/Paul255/ActionFPS-DiscordBOT

**Comment by ScalaWilliam** [comment]
TYVM.

**Comment by ScalaWilliam** [comment]
added to readme
