### ISSUE TITLE
Make the masterserver output a current version

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#205]
So we can solve https://github.com/lucasgautheron/ActionFPS-Game/issues/35#issuecomment-269970636

The version would hardcoded for time being, just make a PR to do an update.

* [ ] Create a value for current version string
* [ ] Output it in the masterserver code.

**Comment by ScalaWilliam** [comment]
@lucasgautheron what is the 'current version'?

**Comment by ScalaWilliam** [comment]
@lucasgautheron what is the current version? This is a 1 line change.

**Comment by lucasgautheron** [comment]
1000

https://github.com/ActionFPS/ActionFPS-Game/blob/master/source/src/cube.h#L61

**Comment by ScalaWilliam** [comment]
And how do we output it? :)

**Comment by ScalaWilliam** [comment]
ie what's the command?

**Comment by lucasgautheron** [comment]
sorry:
current_version 1000

**Comment by ScalaWilliam** [comment]
![screen shot 2017-01-21 at 09 31 07](https://cloud.githubusercontent.com/assets/2464813/22170700/6026711a-dfbc-11e6-83b6-5fa1ff94723d.png)
![screen shot 2017-01-21 at 09 30 56](https://cloud.githubusercontent.com/assets/2464813/22170699/6024e3cc-dfbc-11e6-862f-589632326160.png)
