### ISSUE TITLE
Advertise Tournament January 2017

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#207]
Here's the tournament page: http://challonge.com/actionfps_january_2017
Here's the sign up page: http://challonge.com/tournaments/signup/De0NzGAKVe

* [ ] Replace the Tournaments page with this
* [ ] Add a Bulletin/News item linking to /tournaments/ or to http://challonge.com/tournaments/signup/De0NzGAKVe - whatever you think is better
* [ ] Direct people to Discord for discussion about the tournament
* [ ] Share the info to a non-AF audience
* [ ] Make sure clan IDs are correct in the sign up

Start date: 6pm Germany time, January 6 2017
Single Elimination
Standard AF Clanwar
2 days to complete a cw

Need help in communicating the message better, I'm exhausted ;)

**Comment by DnC-f0r3v3r** [comment]
Lets start working on Week #2
