### ISSUE TITLE
Aura 1337 not reporting

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#214]
* [x] Determine cause
* [x] Fix it

**Comment by ScalaWilliam** [comment]
We receive no log data for 1337.

```bash
$ grep 'local#1337' journal.2016-10-31.5000.log | wc -l
0
```

@Sanzouille: bug @lucasgautheron if you want it fixed :)

**Comment by lucasgautheron** [comment]
The server was down. I restarted it. Can you confirm it is now working again ?

**Comment by ScalaWilliam** [comment]
Confirm lah. Closing.

**Comment by ScalaWilliam** [comment]
https://www.youtube.com/watch?v=IdJ_H4izpeE
