### ISSUE TITLE
Hide or remove points from inactive players

### ISSUE THREAD

**Issue by Paul255** [ScalaWilliam/ActionFPS#216]
Hide or remove points from inactive player. 

![image](https://cloud.githubusercontent.com/assets/7859727/21744707/5352f14e-d51b-11e6-942a-089c9eaab084.png)

**Comment by ScalaWilliam** [comment]
Can you add a justification for it in your ticket?

I use format 'Do X.... So that Y'

**Comment by Paul255** [comment]
Do this to reward active players, to motive and encourage them.

**Comment by ScalaWilliam** [comment]
> And is it possible to make inactive ppl lose more elo points, it's annoying to see people who didn't play since 6 months in the top ^^

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/21744759/d75bea82-d556-11e6-9330-d4f1570ae47e.png)

**Comment by ScalaWilliam** [comment]
Can you figure out a strategy?
I recommend removing points 1 month after player becomes inactive (exponentially?) and rebalance the lost points to all existing players. But not sure how that's work, would need @lucasgautheron  input.

If this issue does not generate a useful outcome, I'll close by 31 January.

**Comment by lucasgautheron** [comment]
What about:
```
display score = real score * max(1, amount of games in the past N weeks / S)
```
Where N is an integer and S a scale factor.
After N weeks without playing, your score goes down to zero.
If you played more than S games in the past N weeks, your displayed score (which is used in the rankings) is equal to your real score.
This way, we avoid decay (they are annoying with ELO systems), and it seems rather easy to implement right ?

**Comment by ScalaWilliam** [comment]
looks reasonable enough.

**Comment by Paul255** [comment]
I like it, what is the average amount of games people play every month (4 weeks) on actionfps ?

**Comment by lucasgautheron** [comment]
![stats](https://cloud.githubusercontent.com/assets/5359646/21787392/41d5f8ee-d6c9-11e6-8495-18ccb6bd18f9.jpg)

**Comment by lucasgautheron** [comment]
Games per week avg over the past 4 weeks, for all players who played at least once in that time span.

![stats](https://cloud.githubusercontent.com/assets/5359646/21787876/da30754a-d6cb-11e6-9593-8a4f5e2a5f0c.jpg)

**Comment by lucasgautheron** [comment]
So let's say:
```
N = 4
S = 8
```
?

**Comment by ScalaWilliam** [comment]
Does the real score get saved? Eg I come back after a 6 month break, get my full score back?

**Comment by Paul255** [comment]
Yes, if you play S games in N weeks !

**Comment by ScalaWilliam** [comment]
This brings their ELO down to 0 :o

Or should they just get unranked?

**Comment by ScalaWilliam** [comment]
What do you think @lucasgautheron @Sanzouille @Paul255 @DaylixX ?

Good to close now?

https://actionfps.com/playerranks/

**Comment by lucasgautheron** [comment]
@ScalaWilliam it is saved, real score is unchanged as before. Only "display score" (used in the rankings) is affected

display score = real score * min(1, amount of games in the past N weeks / S)

**Comment by lucasgautheron** [comment]
Before closing... What about some activity gauge indicator in the list ?
![gauge](https://cloud.githubusercontent.com/assets/5359646/22174248/e37e164a-dfd9-11e6-9d3e-6c67d8055e66.png)
Text = "amount of games in the past N weeks / S" so for instance 3/8 (since we picked S=8)
Background color would range from red (0 games) to green (8/8).
An explanatory text would appear "on hover"

**Comment by ScalaWilliam** [comment]
Separate ticket.

**Comment by ScalaWilliam** [comment]
I'm not so sure about it btw, maybe we can put explanatory text on the Wiki here -> https://github.com/ScalaWilliam/ActionFPS/wiki/Frequently-Asked-Questions

**Comment by ScalaWilliam** [comment]
It's enough that the player is on the list, which indicates his activity tbh

**Comment by ScalaWilliam** [comment]
Closing, as no further comments. If need updates to the functionality, start a new Issue.
