### ISSUE TITLE
Ladder: Fix messed up player timing

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#222]
<img width="521" alt="screen shot 2017-01-08 at 18 15 19" src="https://cloud.githubusercontent.com/assets/2464813/21748979/7114a4c6-d5ce-11e6-9a49-ddc80a545b4c.png">

**Comment by ScalaWilliam** [comment]
Issue is probably caused by combining multiple servers data without segregating them first.

**Comment by ScalaWilliam** [comment]
<img width="550" alt="screen shot 2017-01-09 at 05 48 20" src="https://cloud.githubusercontent.com/assets/2464813/21753800/4a9fd30e-d62f-11e6-87d3-814b4274a4d9.png">

-->

<img width="548" alt="screen shot 2017-01-09 at 05 48 27" src="https://cloud.githubusercontent.com/assets/2464813/21753799/4a73bf30-d62f-11e6-96ee-4e65011c1c58.png">

**Comment by lucasgautheron** [comment]
:+1:
