### ISSUE TITLE
Dynamic tournament list

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#232]
Shouldn't the list of tournaments ideally be dynamic ?
https://actionfps.com/tournaments/

-> We shouldn't need to update it by hand ?

What to display:
 * tournament title
 * whatever creation date / ending date challonge can provide
 * winner if relevant ?

**Comment by ScalaWilliam** [comment]
How about:
```html
<section><h3><a href="https://challonge.com/tourmanet">Tournament title</a></h3>
<object type="image/svg+xml" data="https://challonge.com/tourmanet.svg"></object></section>
```

Sort by: `waiting_start`, `in_progress`, `completed`. Then sort by time (not sure what time though).

**Comment by ScalaWilliam** [comment]
May be useful: #239 (HTTP Client with RFC 7234 support)

**Comment by ScalaWilliam** [comment]
We don't have that many tournaments going. I added a link to Wiki for Tournaments menu item. From the Wiki we can link to all the tournaments.

You mind closing if you're OK with this for the time being? @lucasgautheron

**Comment by ScalaWilliam** [comment]
No response, auto-closing. We don't get enough tournaments to justify this.
