### ISSUE TITLE
Add contrast to signature

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#233]
Poor contrast eg here:

![screen shot 2017-01-10 at 07 54 44](https://cloud.githubusercontent.com/assets/2464813/21788519/26823b52-d70a-11e6-8fe7-733abe86c067.png)

**Comment by ScalaWilliam** [comment]
Typically done with a black text shadow

**Comment by lucasgautheron** [comment]
What do you think of these ? https://www.w3.org/People/Dean/svg/texteffects/index.html

**Comment by ScalaWilliam** [comment]
Whatever works. Can you guys finish this one up? Not a difficult one.

**Comment by ScalaWilliam** [comment]
@DaylixX any update on this? :) 1 small thing.

**Comment by ScalaWilliam** [comment]
or @lucasgautheron

**Comment by lucasgautheron** [comment]
Oh sorry I was about to do it but could not sbt web/run for some reason and gave up x) will do

Envoyé de mon iPhone

**Comment by ScalaWilliam** [comment]
I give this ticket 5 more days, closing after wards.

**Comment by ScalaWilliam** [comment]
tyvm.

**Comment by ScalaWilliam** [comment]
End result:
<img width="550" alt="screen shot 2017-01-25 at 07 41 28" src="https://cloud.githubusercontent.com/assets/2464813/22271894/fbcb11bc-e2d1-11e6-9874-31b5e2316017.png">
