### ISSUE TITLE
Map pool and tiebraker

### ISSUE THREAD

**Issue by Subjective10** [ScalaWilliam/ActionFPS#238]
The map pool includes maps like depot and inudstrials but when you include those maps I see no reason to leave out maps like swamp and / or avenue. (even maps like stellar are pretty good and fastpaced maps. They were made official for a reason I guess) 

Also the way the tiebreaker is defined there is a big chance of dropping on urban, werk or industrial which are biased maps for one side making it pretty unfair for one of the teams.

**Comment by lucasgautheron** [comment]
The experimental, undiscussed choice of competitive map pool employed in the match client is:
```
ac_depot
ac_desert3
ac_elevation
ac_gothic
ac_industrial
ac_ingress
ac_mines
ac_power
ac_shine
ac_sunset
ac_swamp
ac_urban
```
These maps were picked having in mind that we would like to enforce half time team swap in the future, because the current conventional way of proceeding inters and cms is fundamentally unsatisfactory. Unless we played symmetric maps all the time, but we'd rather not do that.

I'll post more statistics that are useful to this discussion very soon

**Comment by Subjective10** [comment]
@lucasgautheron What made u decide on these maps? Like I said there are way more playable maps then those 12.

**Comment by ScalaWilliam** [comment]
Currently on [January 2017 Tournament 2](https://actionfps.blogspot.sg/2017/01/january-2017-tournament-2.html):

```
ac_depot
ac_desert3
ac_elevation
ac_gothic
ac_industrial
ac_ingress
ac_mines
ac_power
ac_shine
ac_sunset
ac_urban
ac_werk
```

So @lucasgautheron has `ac_swamp` and I have `ac_werk`, that's the only difference. What do you say?

**Comment by lucasgautheron** [comment]
```
ac_desert3: 3327 games, 54.1 % CLA, 38.4 % RVSF, 7.5 % ties
ac_ingress: 2642 games, 53.1 % CLA, 39.0 % RVSF, 7.9 % ties
ac_gothic: 2534 games, 35.4 % CLA, 57.5 % RVSF, 7.2 % ties
ac_shine: 1387 games, 44.3 % CLA, 48.5 % RVSF, 7.1 % ties
ac_elevation: 691 games, 53.8 % CLA, 39.2 % RVSF, 6.9 % ties
ac_sunset: 510 games, 49.0 % CLA, 42.5 % RVSF, 8.4 % ties
ac_mines: 390 games, 51.5 % CLA, 38.5 % RVSF, 10.0 % ties
ac_depot: 369 games, 39.0 % CLA, 46.1 % RVSF, 14.9 % ties
ac_werk: 340 games, 59.7 % CLA, 34.7 % RVSF, 5.6 % ties
ac_urban: 329 games, 34.0 % CLA, 59.0 % RVSF, 7.0 % ties
ac_swamp: 269 games, 56.9 % CLA, 34.2 % RVSF, 8.9 % ties
ac_outpost: 226 games, 34.1 % CLA, 50.9 % RVSF, 15.0 % ties
ac_power: 115 games, 56.5 % CLA, 30.4 % RVSF, 13.0 % ties
ac_lainio: 107 games, 41.1 % CLA, 50.5 % RVSF, 8.4 % ties
ac_industrial: 104 games, 39.4 % CLA, 54.8 % RVSF, 5.8 % ties
ac_avenue: 68 games, 45.6 % CLA, 48.5 % RVSF, 5.9 % ties
ac_arid: 42 games, 57.1 % CLA, 35.7 % RVSF, 7.1 % ties
ac_edifice: 26 games, 65.4 % CLA, 30.8 % RVSF, 3.8 % ties
ac_stellar: 22 games, 40.9 % CLA, 59.1 % RVSF, 0.0 % ties
ac_keller: 20 games, 35.0 % CLA, 55.0 % RVSF, 10.0 % ties
ac_iceroad: 18 games, 38.9 % CLA, 50.0 % RVSF, 11.1 % ties
ac_arabian: 12 games, 58.3 % CLA, 25.0 % RVSF, 16.7 % ties
ac_cavern: 10 games, 40.0 % CLA, 40.0 % RVSF, 20.0 % ties
ac_aqueous: 9 games, 55.6 % CLA, 44.4 % RVSF, 0.0 % ties
```

**Comment by lucasgautheron** [comment]
3vs3 only:

| map | games | % games | CLA wins | RVSF wins | ties | biasedness |
| --- | --- | --- | --- | --- | --- | --- |
| ac_desert3 | 1371 | 23.06 % | 51.9 % | 39.4 % | 8.7 % | 0.137 |
| ac_ingress | 1188 | 19.98 % | 57.5 % | 34.5 % | 8.0 % | 0.250 |
| ac_gothic | 998 | 16.79 % | 36.4 % | 55.1 % | 8.5 % | 0.205 |
| ac_shine | 708 | 11.91 % | 42.5 % | 50.3 % | 7.2 % | 0.084 |
| ac_sunset | 268 | 4.51 % | 50.7 % | 42.2 % | 7.1 % | 0.092 |
| ac_elevation | 259 | 4.36 % | 47.9 % | 44.4 % | 7.7 % | 0.038 |
| ac_urban | 210 | 3.53 % | 31.4 % | 61.9 % | 6.7 % | 0.327 |
| ac_mines | 210 | 3.53 % | 55.2 % | 34.8 % | 10.0 % | 0.228 |
| ac_werk | 176 | 2.96 % | 63.1 % | 30.7 % | 6.2 % | 0.345 |
| ac_depot | 152 | 2.56 % | 30.3 % | 52.0 % | 17.8 % | 0.264 |
| ac_swamp | 95 | 1.60 % | 68.4 % | 27.4 % | 4.2 % | 0.429 |
| ac_outpost | 87 | 1.46 % | 36.8 % | 44.8 % | 18.4 % | 0.099 |
| ac_lainio | 53 | 0.89 % | 47.2 % | 45.3 % | 7.5 % | 0.020 |
| ac_power | 48 | 0.81 % | 60.4 % | 29.2 % | 10.4 % | 0.349 |
| ac_industrial | 42 | 0.71 % | 38.1 % | 52.4 % | 9.5 % | 0.158 |
| ac_avenue | 30 | 0.50 % | 46.7 % | 50.0 % | 3.3 % | 0.034 |
| ac_edifice | 12 | 0.20 % | 66.7 % | 33.3 % | 0.0 % | 0.333 |
| ac_keller | 10 | 0.17 % | 20.0 % | 70.0 % | 10.0 % | 0.556 |
| ac_arabian | 9 | 0.15 % | 55.6 % | 22.2 % | 22.2 % | 0.429 |
| ac_iceroad | 6 | 0.10 % | 50.0 % | 33.3 % | 16.7 % | 0.200 |
| ac_stellar | 6 | 0.10 % | 66.7 % | 33.3 % | 0.0 % | 0.333 |
| ac_cavern | 3 | 0.05 % | 66.7 % | 33.3 % | 0.0 % | 0.333 |
| ac_arid | 2 | 0.03 % | 50.0 % | 50.0 % | 0.0 % | 0.000 |
| ac_aqueous | 2 | 0.03 % | 50.0 % | 50.0 % | 0.0 % | 0.000 |

**Comment by lucasgautheron** [comment]
3vs3 only:



| map | games | % games | CLA wins | RVSF wins | ties | biasedness |
| --- | --- | --- | --- | --- | --- | --- |
| ac_desert3 | 1371 | 23.06 % | 51.9 % | 39.4 % | 8.7 % | 0.137 |
| ac_ingress | 1188 | 19.98 % | 57.5 % | 34.5 % | 8.0 % | 0.250 |
| ac_gothic | 998 | 16.79 % | 36.4 % | 55.1 % | 8.5 % | 0.205 |
| ac_shine | 708 | 11.91 % | 42.5 % | 50.3 % | 7.2 % | 0.084 |
| ac_sunset | 268 | 4.51 % | 50.7 % | 42.2 % | 7.1 % | 0.092 |
| ac_elevation | 259 | 4.36 % | 47.9 % | 44.4 % | 7.7 % | 0.038 |
| ac_urban | 210 | 3.53 % | 31.4 % | 61.9 % | 6.7 % | 0.327 |
| ac_mines | 210 | 3.53 % | 55.2 % | 34.8 % | 10.0 % | 0.228 |
| ac_werk | 176 | 2.96 % | 63.1 % | 30.7 % | 6.2 % | 0.345 |
| ac_depot | 152 | 2.56 % | 30.3 % | 52.0 % | 17.8 % | 0.264 |
| ac_swamp | 95 | 1.60 % | 68.4 % | 27.4 % | 4.2 % | 0.429 |
| ac_outpost | 87 | 1.46 % | 36.8 % | 44.8 % | 18.4 % | 0.099 |
| ac_lainio | 53 | 0.89 % | 47.2 % | 45.3 % | 7.5 % | 0.020 |
| ac_power | 48 | 0.81 % | 60.4 % | 29.2 % | 10.4 % | 0.349 |
| ac_industrial | 42 | 0.71 % | 38.1 % | 52.4 % | 9.5 % | 0.158 |
| ac_avenue | 30 | 0.50 % | 46.7 % | 50.0 % | 3.3 % | 0.034 |
| ac_edifice | 12 | 0.20 % | 66.7 % | 33.3 % | 0.0 % | 0.333 |
| ac_keller | 10 | 0.17 % | 20.0 % | 70.0 % | 10.0 % | 0.556 |
| ac_arabian | 9 | 0.15 % | 55.6 % | 22.2 % | 22.2 % | 0.429 |
| ac_iceroad | 6 | 0.10 % | 50.0 % | 33.3 % | 16.7 % | 0.200 |
| ac_stellar | 6 | 0.10 % | 66.7 % | 33.3 % | 0.0 % | 0.333 |
| ac_cavern | 3 | 0.05 % | 66.7 % | 33.3 % | 0.0 % | 0.333 |
| ac_arid | 2 | 0.03 % | 50.0 % | 50.0 % | 0.0 % | 0.000 |
| ac_aqueous | 2 | 0.03 % | 50.0 % | 50.0 % | 0.0 % | 0.000 |

**Comment by lucasgautheron** [comment]
4vs4 only:

| map | games | % games | CLA wins | RVSF wins | ties | biasedness |
| --- | --- | --- | --- | --- | --- | --- |
| ac_power | 40 | 30.30 % | 47.5 % | 35.0 % | 17.5 % | 0.152 |
| ac_shine | 19 | 14.39 % | 31.6 % | 52.6 % | 15.8 % | 0.250 |
| ac_desert3 | 17 | 12.88 % | 64.7 % | 35.3 % | 0.0 % | 0.294 |
| ac_mines | 12 | 9.09 % | 41.7 % | 33.3 % | 25.0 % | 0.111 |
| ac_depot | 9 | 6.82 % | 22.2 % | 66.7 % | 11.1 % | 0.500 |
| ac_ingress | 6 | 4.55 % | 100.0 % | 0.0 % | 0.0 % | 1.000 |
| ac_outpost | 4 | 3.03 % | 75.0 % | 0.0 % | 25.0 % | 1.000 |
| ac_gothic | 4 | 3.03 % | 50.0 % | 25.0 % | 25.0 % | 0.333 |
| ac_lainio | 4 | 3.03 % | 50.0 % | 50.0 % | 0.0 % | 0.000 |
| ac_sunset | 3 | 2.27 % | 66.7 % | 0.0 % | 33.3 % | 1.000 |
| ac_urban | 3 | 2.27 % | 0.0 % | 100.0 % | 0.0 % | 1.000 |
| ac_iceroad | 2 | 1.52 % | 0.0 % | 100.0 % | 0.0 % | 1.000 |
| ac_industrial | 2 | 1.52 % | 0.0 % | 100.0 % | 0.0 % | 1.000 |
| ac_elevation | 2 | 1.52 % | 50.0 % | 50.0 % | 0.0 % | 0.000 |
| ac_avenue | 1 | 0.76 % | 100.0 % | 0.0 % | 0.0 % | 1.000 |
| ac_arabian | 1 | 0.76 % | 100.0 % | 0.0 % | 0.0 % | 1.000 |
| ac_werk | 1 | 0.76 % | 100.0 % | 0.0 % | 0.0 % | 1.000 |
| ac_keller | 1 | 0.76 % | 100.0 % | 0.0 % | 0.0 % | 1.000 |
| ac_swamp | 1 | 0.76 % | 0.0 % | 100.0 % | 0.0 % | 1.000 |

**Comment by Paul255** [comment]
AF is supposed to be innovative, why would we prevent the map choice to be innovative too ?

In my opinion we should allow all maps. We can eventually set up a pool to ban 3 or 4 maps, with a turnover every month ?

**Comment by ScalaWilliam** [comment]
I'd say remove the maps that aren't up to par for whatever reason, and only allow new maps, & remove them if they are not up to par.

**Comment by lucasgautheron** [comment]
@paul255 because some maps are just bad. We don't have to take any shit map. I'm pushing for new maps, but decent maps preferably

**Comment by ScalaWilliam** [comment]
@lucasgautheron Is there some place that newly submitted maps can be evaluated?

**Comment by lucasgautheron** [comment]
Which one would you suggest ? There's none right now.

**Comment by ScalaWilliam** [comment]
(1) ActionFPS/ActionFPS-Maps or ActionFPS/ActionFPS-Media repository or something?  Could be external to the game, to decouple from game releases? Then we can have a self contained place for submitting maps and other media.
(2) Potentially automatically syncable, even, with GitHub :)?
(3) I'd also suggest to remove any crappy maps we have from the game, to remove the noise and make the choice obvious.
(4) We'd end up with very few maps that cannot be played in a tournament, and ppl wouldn't need to wreck their head about it.

What do you say, for each of the points?

**Comment by lucasgautheron** [comment]
The way this discussion is going, it now belongs to AF-Game. I'll post a ticket

**Comment by Paul255** [comment]
@lucasgautheron Who chose if a map is bad or not ? We need ask the player base

**Comment by ScalaWilliam** [comment]
We choose, but can use the player base to guide our decision.

**Comment by lucasgautheron** [comment]
@ScalaWilliam yes to all points, possibly. We need to see if we can make use of the 'autodownload' feature though. Otherwise, we can drop it.

**Comment by ScalaWilliam** [comment]
Let me think up of a good model for this. I'm thinking we could do an Akimbo replica hosted on GitHub. Can generate static HTML & put up onto ac-akimbo.net if you wanted to get immediate and fast exposure.

**Comment by Subjective10** [comment]
Imo the thing that I liked a lot about acwc was the fact we could ban maps out of the small pool you got, being able to counter your opponents a bit.

**Comment by lucasgautheron** [comment]
The problem I am thinking of is that Akimbo packages and group all the
files contained in one entity

So, whatever we do, this packaging step needs to be transparent

**Comment by ScalaWilliam** [comment]
I didn't understand @lucasgautheron

**Comment by lucasgautheron** [comment]
Take a mapmodel for instance. It's made of one or more model files, plus optional config files and skins.
The autodownload systems downloads a mapmodel as a packaged zip and then extracts it.
So, when someone designs content, and submits it, then it will have to be packaged before the autodownload system can take it.
So we need to think whether we want to drop this system or not.

**Comment by ScalaWilliam** [comment]
Can be done automatically in the Git repository. I'm coming up with something right now.

**Comment by ScalaWilliam** [comment]
@lucasgautheron https://github.com/ActionFPS/ActionFPS-Game/issues/39.

**Comment by ScalaWilliam** [comment]
@Subjective10 is that still related to your original posting?

Can you tell us more about the map-banning?

@lucasgautheron I think removing some unbalanced maps until half-time is enforced might be a good idea.

**Comment by Subjective10** [comment]
@ScalaWilliam In ACWC you had a small map pool provided by the orginasors (map pool was different every match) from 5 maps. Every team could ban 2 maps (first team 1 bans, then team 2 bans, team 1 bans and alstly team 2 bans.) The last map left in the pool would be played on both sides, A tiebraker map would be randomly chosen from the banned maps.

**Comment by ScalaWilliam** [comment]
Why do you think it's good to have @Subjective10?

**Comment by Paul255** [comment]
@ScalaWilliam It means more diversity, more fun and more strategy.

For example if you play agains't a team known to be good on a certain map of the map pool you'll ban it, and you'll train others maps. It's fun to watch and play new maps.

**Comment by ScalaWilliam** [comment]
As Map Blocking is a completely separate topic, here's a GitHub Issue for you to discuss --> https://github.com/ScalaWilliam/ActionFPS/issues/247

Are you satisfied @Subjective10 with the outcome and discussion yet or not?

**Comment by lucasgautheron** [comment]
Referring to the initial issue:
I suggest a temporary fix that consists in only allowing shine, elevation and sunset as tie breaker (lowest "biasedness" in 3vs3 and also low tie rate). What do you think?

**Comment by ScalaWilliam** [comment]
Good idea. Let's do that for Tournament 2.
Would you mind updating the rule @lucasgautheron or @Paul255 ?

**Comment by lucasgautheron** [comment]
I don't seem to be allowed to edit other people's articles on the blog. They are grayed in the admin panel.

**Comment by Subjective10** [comment]
As for the map pool I just think every official map should be in the map pool, although a lot of people do not want that. Just adding some maps to the pool would already satisfy me. I think playing sunset on cLA does give an advantage if played correctly but thats maybe just me, Shine and elevation are decent maps when it comes to biasedness. 

For banning / picking I will move to the other topic.

**Comment by ScalaWilliam** [comment]
@lucasgautheron made you admin. Try again.

**Comment by Paul255** [comment]
See #247
