### ISSUE TITLE
Map blocking in Tournament

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#247]
https://github.com/ScalaWilliam/ActionFPS/issues/238#issuecomment-271875263
https://github.com/ScalaWilliam/ActionFPS/issues/238#issuecomment-271899833
https://github.com/ScalaWilliam/ActionFPS/issues/238#issuecomment-272146573

@Subjective10 @Paul255 @lucasgautheron

**Comment by ScalaWilliam** [comment]
Continue discussing here.

**Comment by ScalaWilliam** [comment]
Try out: Tournament 2 or Tournament 3 or not at all?

**Comment by Subjective10** [comment]
Being able to ban maps away from your opponent just gives abilities to counterplay on maps you think you have more chance on.

**Comment by Paul255** [comment]
I suggest we extend the map pool for tournament 3 :

``` 
ac_avenue.jpg
ac_depot.jpg
ac_desert3.jpg
ac_edifice.jpg
ac_elevation.jpg
ac_gothic.jpg
ac_industrial.jpg
ac_ingress.jpg
ac_lainio.jpg
ac_mines.jpg
ac_outpost.jpg
ac_power.jpg
ac_shine.jpg
ac_sunset.jpg
ac_swamp.jpg
ac_terros.jpg
ac_urban.jpg
ac_werk.jpg
```

I removed the 7 less played map in 3v3 CTF, which leave us with 18 maps. Before the match each team could remove 5 maps ?

**Comment by lucasgautheron** [comment]
terros???

**Comment by Paul255** [comment]
Oh yeah didn't see it cuz it was never played, removed

**Comment by Subjective10** [comment]
Map pool looks good imo

**Comment by Paul255** [comment]
Will be tested in the next tournament !

**Comment by ScalaWilliam** [comment]
Plugged into wiki. https://github.com/ScalaWilliam/ActionFPS/issues/257
