### ISSUE TITLE
Off-site INTER Notifications.

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#271]
Should you be on the site to receive an `!inter` notification?

We have the option of push notifications when Actionfps.com is closed.
This could even work on **mobile phones**.

**Comment by ScalaWilliam** [comment]
All detail here: https://github.com/ScalaWilliam/ActionFPS/issues/243#issuecomment-271696287

**Comment by lucasgautheron** [comment]
I'd like it very much to happen.
Ideally, although that's probably too soon, it would be great if you could enable notifications from your "friends" only. Might be less spammy

**Comment by ScalaWilliam** [comment]
:iphone:

**Comment by ScalaWilliam** [comment]
#271 - push notifications. Follow https://documentation.onesignal.com/docs/web-push-sdk-setup-https

**Comment by ScalaWilliam** [comment]
Completed. Works as expected. Using https://onesignal.com
