### ISSUE TITLE
Clan rankings decay

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#278]
So that non-participating clans disappear.
Based on #273.

**Comment by ScalaWilliam** [comment]
iR very inactive for example.
![screen shot 2017-01-24 at 20 13 25](https://cloud.githubusercontent.com/assets/2464813/22246812/9675e11c-e271-11e6-83ed-58240783ceff.png)
![screen shot 2017-01-24 at 20 13 22](https://cloud.githubusercontent.com/assets/2464813/22246811/9672e08e-e271-11e6-9cf4-53538c1216cc.png)

**Comment by lucasgautheron** [comment]
I would have seen it working the same way it was achieved for player ranks ?

**Comment by ScalaWilliam** [comment]
@Paul255  @lucasgautheron can create an issue for that?

Your approach was `* min(1,N(t)/S)`, mine is `*0.5^((t-30d)/30d)`.
I took the latter approach for the ladder. Implementation is a bit easier for the exponential decay, but doesn't completely eliminate the subject from the ranking.
