### ISSUE TITLE
Add GIF animation for game to README.md

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#281]
So people get the idea very quickly.

**Comment by Paul255** [comment]
Test 
![testafps](https://cloud.githubusercontent.com/assets/7859727/22290303/5011123e-e300-11e6-868d-87e980248fc1.gif)

**Comment by ScalaWilliam** [comment]
LGTM. Can you put it in the README in the placeholder?

**Comment by ScalaWilliam** [comment]
PR not needed.

**Comment by Paul255** [comment]
![](http://i.imgur.com/e7x20xK.gif)

**Comment by Paul255** [comment]
![afps](https://cloud.githubusercontent.com/assets/7859727/22341064/cf58a7c4-e3ef-11e6-9350-bc6f8ae4647a.gif)
![afps2](https://cloud.githubusercontent.com/assets/7859727/22341068/d125b664-e3ef-11e6-9cf9-6cf6a2c113d2.gif)

**Comment by Paul255** [comment]
Just need good video, under 10 sec ^^

**Comment by lucasgautheron** [comment]
the bandicam.com thing is a no-no
and blackbars could be avoided
maybe try with ffmpeg

**Comment by lucasgautheron** [comment]
the bandicam.com thing is a no-no
and blackbars could be avoided
maybe try with ffmpeg

**Comment by ScalaWilliam** [comment]
Added in whatever we have - if you don't like it, make another Issue to fix it.
