### ISSUE TITLE
Fix wordpress design

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#282]
As it's quite bad and ugly.

Most likely just a choice of template and a few small edits.

**Comment by DaylixX** [comment]
Template test:
https://actiontestblog.wordpress.com/
Logo:
![actionfpslogo2 copie](https://cloud.githubusercontent.com/assets/16243477/22311379/87109c5c-e353-11e6-81dd-a8d7cd5d426b.png)
Favicon :
![2actionrd256x copie](https://cloud.githubusercontent.com/assets/16243477/22311400/a02a78b6-e353-11e6-9dce-97998295223e.png)
Palette Color:
Grey and Red
Headings:
Unbutu (Regular, Normal Size)
Base Font:
Alegreya (Normal Size)
Site title:
ActionFPS
Tagline:
an AssaultCube Competitive League
Footer Credit:
Default

**Comment by ScalaWilliam** [comment]
@DaylixX I sent you a wordpress invitation to change it.

**Comment by DaylixX** [comment]
@ScalaWilliam I can edit post and moderate comments but i can't edit the blog design

**Comment by ScalaWilliam** [comment]
Please try now @DaylixX

**Comment by DaylixX** [comment]
its good =) @ScalaWilliam

**Comment by ScalaWilliam** [comment]
You keep the admin privileges :)

**Comment by DaylixX** [comment]
i think its good : https://actionfps.wordpress.com/

**Comment by ScalaWilliam** [comment]
LGTM. I'll close. Thanks very much for the contribution.
