### ISSUE TITLE
Firefox layout issues

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#285]
https://drive.google.com/open?id=0ByqVpjadKNSdQ2RMSHNpZ0RIQkU

**Comment by ScalaWilliam** [comment]
I don't have time for this, if nobody picks it up I'll just close in 7 days. So try to find somebody to do this ;)

**Comment by Paul255** [comment]
Temp fix : CTRL + "+" ?

**Comment by ScalaWilliam** [comment]
![screen shot 2017-02-04 at 12 05 20](https://cloud.githubusercontent.com/assets/2464813/22615578/4310ac82-ead2-11e6-9c4d-284f7e0607bf.png)
