### ISSUE TITLE
No link to actionfps.com from actionfps.wordpress.com

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#289]
Someone who comes to the blog might want to go straight to actionfps via one click, but now there's no way except through 'Servers'.

**Comment by DaylixX** [comment]
Done !

Home • > http://actionfps.com
Tournaments • > Blog post

**Comment by ScalaWilliam** [comment]
Now that'll be a bit confusing! ;)

How about:
* HOME -> https://actionfps.wordpress.com/
* ACTIONFPS.COM -> https://actionfps.com/
* Tournaments -> https://github.com/ScalaWilliam/ActionFPS/wiki/Tournaments

I'll try to be more explicit next time.

**Comment by DaylixX** [comment]
Done !

**Comment by ScalaWilliam** [comment]
Good thank you 👍
