### ISSUE TITLE
Tournament: for forfeits, add a Text attachment explaining the reason

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#290]
So that people know why they happened.

**Comment by ScalaWilliam** [comment]
And document it in tournament checklist

**Comment by Paul-Michaud** [comment]
Do we want to auto-forfeit after 2 days without the game being played ?

**Comment by ScalaWilliam** [comment]
More important would be to publish the forfeiture date than auto-forfeit.

**Comment by ScalaWilliam** [comment]
Flushed the info here: https://github.com/ScalaWilliam/ActionFPS/wiki/Tournaments#progressing-tournament-checklist
