### ISSUE TITLE
Change Teamspeak for Discord

### ISSUE THREAD

**Issue by DaylixX** [ScalaWilliam/ActionFPS#293]
Update:
- https://actionfps.com/play/
- maybe change teamspeak for discord ?

**Comment by DaylixX** [comment]
And remove it from: https://github.com/ScalaWilliam/ActionFPS/wiki/Frequently-Asked-Questions

**Comment by lucasgautheron** [comment]
Fixed by https://github.com/ScalaWilliam/ActionFPS/commit/fbc3a6fa34385eae8c54dd2d3b03e415e5eaf7bc

**Comment by DaylixX** [comment]
![image](https://cloud.githubusercontent.com/assets/16243477/22436343/eb3b703e-e723-11e6-891b-f85ec6a17274.png)

WTF ?

**Comment by lucasgautheron** [comment]
I asked you to make a smaller image in #70

**Comment by lucasgautheron** [comment]
:thumbsup:

**Comment by ScalaWilliam** [comment]
Please associate commit descriptions with an Issue next time :)

**Comment by lucasgautheron** [comment]
I know, I just forgot..
