### ISSUE TITLE
!public notification for ActionFPS-Game / ladder server

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#299]
So that we'd get more activity in the ladder for the new game.

**Comment by ScalaWilliam** [comment]
what do you think

**Comment by lucasgautheron** [comment]
not a priority in my opinion, but you know better how much time it would take you

**Comment by Sanzouille** [comment]
Finding a way to attract new players on the ladder is a top priority but I'm  not sure this is the way to do it

**Comment by ScalaWilliam** [comment]
Thanks, will close & postpone.
