### ISSUE TITLE
Unify /register-play/ and /play/ into /play/

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#305]
So that:

* User experience is better
* We can make changes more swiftly

**Comment by ScalaWilliam** [comment]
![ejwfwuksgyaqamc_cgebgzbxnwiipjryqk6p_d3dx_f5trgifc57lfqxy-t-fdvmf1krqvxezpruy6jcl53mthm_6nsodz4nc7too8mrgaogemggcdra4nhf0qsbwoisxajwkl03uwzrzq0emvzxgzmk6apzgop1n_h7a5pwkpk](https://cloud.githubusercontent.com/assets/2464813/22618233/26ad7b5c-eb12-11e6-8851-67b3681aa310.jpeg)

**Comment by lucasgautheron** [comment]
shouldn't signup (if not logged in) come first ? otherwise ppl might install the game, open it and wonder wtf to do

**Comment by ScalaWilliam** [comment]
Yes. sorry, the flow is under the horizontal line :p

**Comment by lucasgautheron** [comment]
Oh my bad. Alright then!
