### ISSUE TITLE
latest release should show the date & name

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#306]
So that the user knows if there's been an update & when it's been last.

**Comment by ScalaWilliam** [comment]
Provide latest release date.

**Comment by ScalaWilliam** [comment]
GET         /download-direct/release-date           @controllers.DownloadsController.releaseDate
GET         /download-direct/release-version        @controllers.DownloadsController.releaseVersion

**Comment by ScalaWilliam** [comment]
<img width="595" alt="screen shot 2017-02-05 at 11 26 02" src="https://cloud.githubusercontent.com/assets/2464813/22623434/f3c04b50-eb95-11e6-93f7-f0c60246e3ad.png">
Nice :)

@lucasgautheron fyi

**Comment by lucasgautheron** [comment]
Very nice! :D
