### ISSUE TITLE
Servers: show server table with updates

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#313]
So it's easier to get a full picture.

**Comment by ScalaWilliam** [comment]
Together with #292.

**Comment by lucasgautheron** [comment]
Excellent!

**Comment by ScalaWilliam** [comment]
<img width="267" alt="screen shot 2017-02-06 at 23 09 19" src="https://cloud.githubusercontent.com/assets/2464813/22652421/5cc7d07e-ecc1-11e6-8150-3ebe497214d5.png">
