### ISSUE TITLE
SVG ActionFPS Icon

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#316]
Vectorial format should be much more convenient to work with.

**Comment by ScalaWilliam** [comment]
And logo

**Comment by DaylixX** [comment]
I work on this

**Comment by DaylixX** [comment]
![1](https://cloud.githubusercontent.com/assets/16243477/23094916/cdea73d0-f601-11e6-8a00-9e2e87c0b274.png)
![2](https://cloud.githubusercontent.com/assets/16243477/23094917/cdec2978-f601-11e6-86d3-7dc7192926df.png)
![3](https://cloud.githubusercontent.com/assets/16243477/23094918/cdee83bc-f601-11e6-8e73-7ffd1e0e2aa0.png)
![4](https://cloud.githubusercontent.com/assets/16243477/23094920/cdf44176-f601-11e6-8982-f8d062329451.png)
![5](https://cloud.githubusercontent.com/assets/16243477/23094919/cdf116a4-f601-11e6-88a6-d75849e4047e.png)
![6](https://cloud.githubusercontent.com/assets/16243477/23094921/ce01380e-f601-11e6-8b66-7284cc8510f4.png)

**Comment by DaylixX** [comment]
For Download the .zip / I can't Upload it on Git.
http://www.actioncu.be/files/AFPS.zip

**Comment by DaylixX** [comment]
Again for the Icon. I can't Upload idk for what....
http://www.actioncu.be/files/iconAFPS.zip

**Comment by ScalaWilliam** [comment]
Thanks for this @DaylixX  but this is vector that embeds raster images... can you send the original source file (Illustrator?)?

**Comment by DaylixX** [comment]
Yeah.
http://www.actioncu.be/files/actionICON256px.zip
http://www.actioncu.be/files/actionfpsLOGO.zip

**Comment by ScalaWilliam** [comment]
Thank you @DaylixX ! :)
