### ISSUE TITLE
Live games are not shown

### ISSUE THREAD

**Issue by gyunderscorebe** [ScalaWilliam/ActionFPS#320]
Games in progress don't seem to be shown on the website anymore. E.g. I am on aura 1999 right now and there is no live game card on the site.

**Comment by Sanzouille** [comment]
need @ScalaWilliam expertise for this

**Comment by gyunderscorebe** [comment]
Currently live games are shown correctly.

**Comment by ScalaWilliam** [comment]
Just had to restart the server, but weird that it's not working again (I added an auto sub-process restart)

**Comment by gyunderscorebe** [comment]
It's still doesn't work sometimes, weird.

**Comment by ScalaWilliam** [comment]
Does it randomly recover as well?

**Comment by ScalaWilliam** [comment]
No issue reported again, so closing.
