### ISSUE TITLE
No background on Signature ?

### ISSUE THREAD

**Issue by DaylixX** [ScalaWilliam/ActionFPS#322]
See here : https://actionfps.com/player/signature.svg?id=underarm

**Comment by ScalaWilliam** [comment]
The user has no favourite map. What do you propose to have as background for such a user?

**Comment by DaylixX** [comment]
Why not this picture ? 

![missingcontent](https://cloud.githubusercontent.com/assets/16243477/26213212/828fda3c-3bf8-11e7-9888-a8c1743e0bdb.png)

**Comment by ScalaWilliam** [comment]
Someone wanna integrate the image above?

**Comment by DaylixX** [comment]
not especially, but it's always better than nothing. Or you prefer I work on image really based on assaultcube ?

**Comment by ScalaWilliam** [comment]
This image is fine.

**Comment by DaylixX** [comment]
OK so i close
