### ISSUE TITLE
Terrible game to require flags == 0

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#325]
As this doesn't appear like a terrible game to me.
https://actionfps.com/game/?id=2017-03-04T12:33:17Z

**Comment by lucasgautheron** [comment]
Nice try, still a terrible game :P

**Comment by ScalaWilliam** [comment]
1 flag wouldn't consider terrible

**Comment by lucasgautheron** [comment]
Yes, I don't think it means much, 15 frags and more than 30 deaths means you were probably a burden, even if you scored one flag (maybe you stole it 2 cubes away from scoring also xD)

**Comment by lucasgautheron** [comment]
But idc so much
