### ISSUE TITLE
Give access to motd to ladder cops

### ISSUE THREAD

**Issue by tejlibre** [ScalaWilliam/ActionFPS#337]
Have a way to manage motd would be useful for example in the following cases 
1. to announce significant changes that could affect players, logged information is in public space
2. link to website and discord for people asking for help. While the website provides link to discord, i think its better to give it straightaway on motd
3. tournament winners

**Comment by ScalaWilliam** [comment]
There's a problem, I can see there's MOTD file `motd_en.txt` but motd is also defined in `servercmdline.txt` as:
` -o www.woop.us - Aura 1  - Make sure to register on...`

I'm not sure how to configure MOTD to be loaded from file.

**Comment by tejlibre** [comment]
I guess adding the current commandline option to config/motd should work.
Or using -Oconfig/**file** and creating the **file**_en.txt

From the docs: http://assault.cubers.net/docs/commandline.html

-Of	Changes the location of the MOTD (message of the day) filename prefix. The server automatically adds "_en.txt" as a suffix to complete the filename. 
The default is: -Oconfig/motd 
The MOTD will only be read from a file if the -o argument hasn't been specified.

**Comment by ScalaWilliam** [comment]
Okay. I'm just wondering are these configuration files automatically reloaded or does the server need to be restarted?

@Sanzouille and @lucasgautheron: I need to know how you launch Aura servers currently, so that I could integrate them into https://github.com/ActionFPS/WiredAF provisioning workflow.

**Comment by tejlibre** [comment]
I tried it by spinning up a server, but the configuration file wasnt reloaded, not on player reconnect, not on next map but ok after restart. As opposed to blacklist which reloads every minute as reported here https://github.com/ActionFPS/blacklist/commit/dc33417b494d6c0199d5bafcf3efe99aa73ce1fd

**Comment by ScalaWilliam** [comment]
I wonder if MOTD is reloaded automatically? In that case it can live next to the blacklist files.

Basically if something needs a server restart then procedure will be different from something that doesn't need a restart.

**Comment by ScalaWilliam** [comment]
Well I have done the following:
- Set up an explicit config for public server roles https://github.com/ActionFPS/WiredAF/tree/master/roles/ac-public-server
- Set up an explicit config for private server roles https://github.com/ActionFPS/WiredAF/tree/master/roles/ac-private-server
- Added command for copying motd_en from https://github.com/ActionFPS/blacklist/ to https://github.com/ActionFPS/WiredAF/blob/master/roles/ac-sync-blacklist/files/sync-blacklist.sh#L5

So you should be able to take this over and finish up. 

I'll go to sleep, I'm super burnt out right now.

**Comment by ScalaWilliam** [comment]
Closing as this is now in @tejlibre's court. Make a PR to WiredAF and I'll merge.
