### ISSUE TITLE
Incomplete clanwar question 404

### ISSUE THREAD

**Issue by tejlibre** [ScalaWilliam/ActionFPS#383]
When a clan war is incomplete, there is an exclamation mark with a hyperlink to https://actionfps.com/questions/#completed-clanwar and that page doesnt exist.

Could be a page to explain clan war logic, requirement to complete clan war
https://github.com/ScalaWilliam/ActionFPS/blob/master/clans/clanwars/pure-clanwar/src/main/scala/com/actionfps/clans/Clanwar.scala

I think it goes like this

- must use clan tag/actionfps id
- 2 to 3 games to decide a clan war (3rd game needed if first 2 games went 1-1)
- same number of players in all 3 games

**Comment by ScalaWilliam** [comment]
Thanks for this!

There's this page here: https://docs.actionfps.com/glossary.html#clanwar

I'd suggest to make a PR fixing the link to point there, and then [updating the book](https://github.com/ActionFPS/ActionFPS-Book/blob/master/glossary.md) separately.

**Comment by tejlibre** [comment]
404 link is fixed: https://actionfps.com/clanwar/?id=2017-05-16T12:33:30Z

Im not sure how to update the book; the book page has hyperlinks, but not github
https://github.com/ActionFPS/ActionFPS-Book/blob/master/glossary.md
https://docs.actionfps.com/glossary.html

**Comment by ScalaWilliam** [comment]
Not sure what you mean, but docs.actionfps is generated from the actionfps-book repo.

**Comment by ScalaWilliam** [comment]
Closed by #384 and https://github.com/ActionFPS/ActionFPS-Book/pull/8
