### ISSUE TITLE
Clan pictures

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#39]
Define a standard for clan pictures (e.g. size, like 64x64), and let clan players send us one for their clan if they want.

**Comment by lucasgautheron** [comment]
For the clans which didn't provide a picture, we have 3 solutions : 
 * Don't display any picture
 * Display a static placeholder
 * Display a randomly generated picture

We had kind of agreed to use the latter in a previous discussion.
We still need to discuss how we want it to work. 

Example : http://woop.ac:81/html/clan_picture.php?name=MyS&id=mys
Drakas stated he doesn't want transparency

Any ideas ?

**Comment by Sanzouille** [comment]
what we have right now is perfect
