### ISSUE TITLE
Log stream/clone fails with 401 error

### ISSUE THREAD

**Issue by jasbrake** [ScalaWilliam/ActionFPS#391]
When trying to stream the logs with or without an Authentication header, it fails with a 401 error.

```
$ actionfps-clone-logs afps.tsv
Reading file afps.tsv...
Resuming from time 2016-01-02T03:04:05Z, with 0 lines at this time
EventSource error:  {"type":"error","status":401}
```

However, a version that has been running using an authorization header + a process manager to keep it reconnecting is still live streaming the logs. Also the web version available at [ActionFPS Dashboard](https://actionfps.github.io/dashboard/) still works as well. I noticed that it appeared to be using the URL `https://actionfps.com/logs/stream/` instead of `https://actionfps.com/logs`. However when I try to use that URL instead I still get a 401.

**Comment by ScalaWilliam** [comment]
You need a new token. The existing session isn't going to terminate automatically however.

**Comment by jasbrake** [comment]
So it can't be used without a token? The steps in the readme of [actionfps-clone-logs](https://github.com/ActionFPS/actionfps-clone-logs) fails.

**Comment by ScalaWilliam** [comment]
Oh wait hmm that's actually another problem actually, you're using an out of date token.

I shared one on #tribunal.

**Comment by ScalaWilliam** [comment]
Also there's an old logs period, that I introduced and didn't document:
https://github.com/ScalaWilliam/ActionFPS/blob/master/log-server/app/controllers/LogController.scala#L42-L49

**Comment by ScalaWilliam** [comment]
for public access you can't go beyond 3 months, and  af-clone-logs starts a bit earlier than that

**Comment by jasbrake** [comment]
Ohh that makes sense. So if I try to use a date that's too old, I will get 401 Unauthorized. And with authentication was failing because my token was out of date. Thanks @ScalaWilliam.

**Comment by jasbrake** [comment]
And that also explains why the web version still works because it was starting from the present.

**Comment by jasbrake** [comment]
Reopening this since I can't reopen #394.

As mentioned in #407, it stopped working for me at `2017-10-18T09:26:48Z`. The new token issued on November 6th fails with the same behavior (401 error).

This time could correspond with 9d8f808 or c7ef5ee.

Was anything else related to log access authorization changed within the last month?
