### ISSUE TITLE
Log fetch results in error

### ISSUE THREAD

**Issue by gyunderscorebe** [ScalaWilliam/ActionFPS#394]
Both `curl  'https://actionfps.com/logs.tsv?from=2017-06-12T00:00:00Z&to=2099-04-10T11:02:03Z'` and  `curl -H 'Authorization: Bearer <token>' 'https://actionfps.com/logs.tsv?from=2017-06-12T00:00:00Z&to=2099-04-10T11:02:03Z'` result in an error, e.g.

```html
<body>
    <h1>Oops, an error occurred</h1>

    <p id="detail">
        This exception has been logged with id <strong>74f0df64o</strong>.
    </p>

</body>
```

**Comment by ScalaWilliam** [comment]
Thanks for the report. I'm sorry this has been in your way of getting work done.

Closed by 78a33ce5ef6ea2075b8b3cdd017deb967075f6f3

**Comment by ScalaWilliam** [comment]
Actually you close if you're satisfied :-)

**Comment by gyunderscorebe** [comment]
I'm satisfied because version with auth token works, but it still fails without token.

**Comment by ScalaWilliam** [comment]
Please verify & close if happy.

**Comment by gyunderscorebe** [comment]
Don't have a token right now, but token-less version currently fails.
