### ISSUE TITLE
jwtSession stuff is unstable.

### ISSUE THREAD

**Issue by gitchiu** [ScalaWilliam/ActionFPS#396]
From 19650badc2513544601ae4004793c4ea37807066 by @ScalaWilliam:

`request.headers.get(JwtSession.HEADER_NAME).map(sanitizeHeader).map(JwtSession.deserialize).getOrElse(JwtSession())`
is causing real problems because I want to know whether a Jwt token is set - and now it turns out the default value
is not considered empty!

Due to #394.

**Comment by ScalaWilliam** [comment]
Was related to #394 
Fixed by c7ef5ee90961c0ca6273e5c8cb9a52c86f68a40b & 19650badc2513544601ae4004793c4ea37807066
