### ISSUE TITLE
[Scala] Disable demo links in game cards

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#397]
As they 404 right now & the fix is not within this repository.

Related: https://github.com/ScalaWilliam/ActionFPS/issues/324

Example: https://actionfps.com/game/?id=2017-06-28T11:35:34Z 
click 'demo'.

It's simplest to locate the place that defined the demo link (somewhere in the scala code) and set it to `None`.

Scala work. Offering $5 as this is really easy. Issue is posted here too: http://work.scalawilliam.com/remove-demo/

**Comment by neysofu** [comment]
Working on it. Should I leave them in the static and remove them with Scala or just nuke all the links?

**Comment by ScalaWilliam** [comment]
Set statically to `None`.

**Comment by ScalaWilliam** [comment]
This piece of work is still available, if anybody else wants to take on it.

**Comment by ScalaWilliam** [comment]
@neysofu

**Comment by neysofu** [comment]
Sorry, I never got the time to finish it off. 😐

**Comment by ScalaWilliam** [comment]
This task is still available, anyone else can pick it up :-) good started task for this project & very easy to get paid.

**Comment by ScalaWilliam** [comment]
Did it myself ^

**Comment by neysofu** [comment]
Nice :)
