### ISSUE TITLE
Migrate to usage of Compile-time dependency injection

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#400]
So that:
- We understand the tradeoffs and gain knowledge
- Improve robustness
   - As I've had many runtime failures so far
   - As there's no single entry point, which still feels weird

The work **must** be done incrementally. Here, the first unit of work is: "**Application Loader module**" I will pay for this work. http://work.scalawilliam.com/Play-Compile-DI/

If nobody is interested, I'll do this myself when I find the time.

**Comment by ScalaWilliam** [comment]
Reading:
- https://www.playframework.com/documentation/2.5.x/ScalaCompileTimeDependencyInjection
- https://stackoverflow.com/questions/41987974/play-runtime-di-disadvantages
- https://github.com/adamw/macwire (honestly would rather do without it though)

**Comment by ScalaWilliam** [comment]
@omainegra is taking on this piece of work.

**Comment by ScalaWilliam** [comment]
Url updated http://work.scalawilliam.com/Play-Compile-DI-Application-Loader/

**Comment by ScalaWilliam** [comment]
@omainegra I recommend to open a PR as soon as you start, so you get earlier feedback from me.

**Comment by omainegra** [comment]
@ScalaWilliam First PR done, just the *Application Loader* with fallback to *Runtime DI*, as said in the specifications of the job.

**Comment by ScalaWilliam** [comment]
Closed by: https://github.com/ScalaWilliam/ActionFPS/pull/404
