### ISSUE TITLE
Need a new auth token

### ISSUE THREAD

**Issue by jasbrake** [ScalaWilliam/ActionFPS#407]
For log streaming and stuff. Much appreciated :)

**Comment by ScalaWilliam** [comment]
Perhaps I should implement static tokens rather than JWT... The expiration thing is stupid: you either have to set a short time & renew often - or give out a token that lasts forever - or implement a revocation system.

**Comment by jasbrake** [comment]
If it was widely used, it would be cool to have some kind of token generator connected to our ActionFPS accounts that allowed us to generate our own "app tokens" as long as our account had permission to do so. However, since only a few people use this static tokens make sense.

**Comment by jasbrake** [comment]
It looks like around `2017-10-18T09:26:48Z` my token stopped working and I ended up receiving a lot of `0.0.0.0` instead of full IPs.

Nothing changed on my end as far as I can tell and my token shouldn't be up for expiration yet as you gave me a fairly long one. Could this be related to #420? Thanks.
