### ISSUE TITLE
Re-integrate server-pinger Scala/SBT project

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#417]
**Rules: http://work.scalawilliam.com/rules/**

--

As there's no benefit to having it as a separate library. Similar to #408 but a little simpler due to no subprojects to manage.

- Git/SBT project: https://github.com/ActionFPS/server-pinger
  - Take SP repo and move its root contents into a sub-directory `server-pinger`.
  - Merge new SP repo into ActionFPS repo (this repo) using this technique https://stackoverflow.com/a/10548919 (but put into `server-pinger` directory).
  - Integrate SP's `build.sbt` into ActionFPS `actionfps.sbt`, excluding all the publishing features. No `built.sbt` should remain afterwards. Put dependencies into `Dependencies.scala`.
  - Remove reference to server-pinger in `Dependencies.scala` of the SBT build, instead referring to the local project
  - Make sure README.md is up to date.
  - I may have missed something else that needs to be removed, so scope may creep a little
- Remove references from Docs: https://github.com/ActionFPS/ActionFPS-Book/blob/master/portal-development-guide.md

I'll pay $30 for this ([ScalaWilliam Work](http://work.scalawilliam.com/integrate-project-pinger-back/)).
Please post here "**I'm taking on this**" to lock the task to yourself.

**Comment by omainegra** [comment]
I'm taking on this

**Comment by ScalaWilliam** [comment]
If two tasks are similar, I recommend starting on the next one only after first one is finished. I'll update that into the rules. I have some comments and questions

**Comment by ScalaWilliam** [comment]
I think I need to not post a task until I'm 100% certain of the assumptions and lessons from the previous one too :-)

**Comment by ScalaWilliam** [comment]
@omainegra 2 weeks, I'll introduce a new rule for a 2 week limit :-)
If you can't do this at this time please unassign yourself.

**Comment by omainegra** [comment]
@ScalaWilliam Sorry about that, I sent you an email asking you when should I start, based in your previous comment (**100% certain of the assumptions and lessons from the previous on**).

**Comment by ScalaWilliam** [comment]
Oh!

Sorry about that!

Yes, do do that, continue, based on the lessons in the previous issue :-)
