### ISSUE TITLE
Make GraphViz or PlantUML architectural diagram

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#429]
Put it in `/docs/architecture.dot` or `/docs/architecture.plantuml`. Make sure to reference this issue in your PR.

Here's the original:
https://docs.google.com/drawings/d/1fGcN6fcKC_oCL1KtC_-pmWCT_1Da-ka0nijrzUuxiyw/edit

- Conserve the arrows.
- Ensure that the "multiple" indicators eg "Clan repository" are demonstrated somehow.
- Ensure that they are grouped somehow when displayed.

I will pay US$15 for this via ScalaWilliam Work.
**Lock the work** to yourself by saying "I'm taking on this".
Read the rules: http://work.scalawilliam.com/rules/
Work item: http://work.scalawilliam.com/graphviz-plantuml-arch-diagram/

**Comment by rdmueller** [comment]
I'm taking on this

**Comment by rdmueller** [comment]
![actionfps](https://user-images.githubusercontent.com/1856308/32138373-cb69581e-bc31-11e7-8c40-41095a9b5293.png)

**Comment by ScalaWilliam** [comment]
@rdmueller the syslog bit or 3 nodes belongs in a separate part by itself. You could call it "log collection".

**Comment by ScalaWilliam** [comment]
Thanks @rdmueller
