### ISSUE TITLE
Integrate SBT project structure diagram producer into the project

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#431]
Skills required: SBT, Scala

At the moment I'm using this funky hack with [JetBrains sbt-structure](https://github.com/JetBrains/sbt-structure) and some XSLT (Saxon) here:
https://github.com/ActionFPS/dev-doc/blob/master/Makefile

This requires a graphviz, sbt and coursier installation. Usage is: `sbt SBT_REPO=/path/to/ActionFPS`.

What I'm looking instead to do is to self-contain it and have something that could automatically generate it from inside the project itself.

I'd like a root project SBT task definition within this project called `generateXmlStructure` and `generateDotStructure`. I intend to use the XML structure at some point.

**Purpose: Documentation. The Dot structure I use to generate a nice looking graph with URLs to the GitHub source code, as per demonstration here: https://actionfps.github.io/dev-doc/structure.svg**

Demo:
<img width="808" alt="screen shot 2017-10-29 at 08 47 09" src="https://user-images.githubusercontent.com/2464813/32139765-c7ff1a02-bc85-11e7-9018-83bb1500201c.png">

There's https://github.com/jrudolph/sbt-dependency-graph but it seems to generate something rather different from what I want, eg per-project full dependencies, creating multiple files.

I'll pay US$25 for the completion of this task via [ScalaWilliam Work](http://work.scalawilliam.com/). As per the [rules](http://work.scalawilliam.com/rules/), type "**I agree to the [rules](http://work.scalawilliam.com/rules/) and am taking on this task**" to lock this task to yourself.

Work item is here: http://work.scalawilliam.com/integrate-sbt-project-diagram/

**Comment by laughedelic** [comment]
I agree to the rules and am taking on this task
