### ISSUE TITLE
Auto-generate PlantUML SVG that is currently statically generated.

### ISSUE THREAD

**Issue by gitchiu** [ScalaWilliam/ActionFPS#437]
From ef4ab49771b8fe68e14a0d6751cb8c13f3a12068 by @ScalaWilliam:

Currently, `/docs/architecture.plantuml` is generated into `/web/dist/www/af-arch-plant.svg` by hand.
In Play, it's served currently [via static file](https://github.com/ScalaWilliam/ActionFPS/commit/ef4ab49771b8fe68e14a0d6751cb8c13f3a12068#diff-97ed1d45a9e9d6e78017456c16516f5aR22). [This is how it looks online](https://actionfps.com/development/#architecture).

The process involves:
1. Go to http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
2. Paste the plantuml source code
3. Click Submit
4. Click 'View as SVG'
5. Paste it into the SVG file.

There are two points at which we can do the generation:
1. Build-time (SBT)
2. Run-time (Play)

There are multiple ways of doing it as well:
1. Using plantuml JAR - http://www.mvnrepository.com/artifact/net.sourceforge.plantuml/plantuml - while it's self-contained, I don't know how well it does with memory leakages.
2. Using plantuml as an external command eg `java -jar plantuml.jar ...`.
3. Using plantuml HTTP API - unfortunately it uses some funny JS hacks to compress & then base64-like encode the stuff before passing it to the PlantUML url. [Here's how it's implemented](http://plantuml.com/pte). Note that ~~I won't serve directly from plantuml.com because it's HTTP and actionfps.com is HTTPS~~ https://twitter.com/PlantUML/status/926742305750388736.
4. Using Gravizo rendering - http://www.gravizo.com/ - and perhaps then replacing it with a non-proprietary implementation that generates plantuml HTTP API on glitch.me that other people can use for themselves.

Goal of this is to implement the best approach to doing this rendering automatically without intermediate steps.

It would be nice to be able to edit the plantuml source and automatically see it reflected in the ActionFPS development page output when I'm doing `sbt web/run`. This task may require **Play** knowledge.

If you have suggestions for a better approach, do share them and then we can change the ticket around. There is possibility of scope-creep here but I'll try my best to segregate the work.

For this work [I'll pay US$35](http://work.scalawilliam.com/automate-plantuml-render/). If you want to do this, comment: "**I am taking on this task per [ScalaWilliam Work Rules](http://work.scalawilliam.com/rules/)**".

**Comment by laughedelic** [comment]
I am taking on this task per ScalaWilliam Work Rules.
I'm going to do it with the PlantUML Java dependency. I don't see any point in using remote rendering if it can be done locally and integrated with the build process.
