### ISSUE TITLE
Centralized server management

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#45]
* Servers configuration, launch, etc. should be done by actionfps
 * Use SSH and/or syslog to retrieve logs, demos, setup the configuration, start permanent servers or on-demand servers
 * Ability to deploy any version (AC Vanilla, match server, etc)

**Comment by ScalaWilliam** [comment]
Moving to https://github.com/ScalaWilliam/ActionFPS/wiki/Centralised-server-management
