### ISSUE TITLE
Clanwar JSON is missing lots of data

### ISSUE THREAD

**Issue by gitchiu** [ScalaWilliam/ActionFPS#456]
From 222016a95d5d0791bf837aac92e2c6be42780b4c by @ScalaWilliam:

I did this as part of the refactoring to make clanwars more generic
This will of course produce a substantially smaller and poorer data-set
than we had before. There's refactoring/generisation work to be done
before we can supply nice data again.

**Comment by ScalaWilliam** [comment]
Replaced by #458
