### ISSUE TITLE
A few achievements are not working

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#46]
http://actionfps.com/game/?id=2015-12-19T05:31:38Z > Fede should have got the butcher achievement for this but he didn't.
Apparently tosok and or tdm games didn't get counted as well. (Lucky Luke and TDM Lover achievements)

**Comment by lucasgautheron** [comment]
He did it again and still no butcher :D 
http://actionfps.com/game/?id=2015-12-22T04:07:23Z

**Comment by lucasgautheron** [comment]
Honor achievements on woop.ac : http://woop.ac/player/?id=honor
on ActionFPS : http://actionfps.com/player/?id=honor

**Comment by lucasgautheron** [comment]
>  First page said Million got the Maverick achievement on his last game
> when he should have got butcher
> but his profile says he doesn't have maverick

**Comment by ScalaWilliam** [comment]
There is no bug. Enemy team has to have at least 1 registered player to prevent abuse.

https://github.com/ScalaWilliam/ActionFPS/blob/64a457791dd65adb21ada8ef27ccce50a175b0ee/achievements/src/main/scala/acleague/ranker/achievements/immutable/Slaughterer.scala#L27

**Comment by lucasgautheron** [comment]
Thanks :+1:
