### ISSUE TITLE
Live game display issue

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#48]
In case at least one player is in team "CLA-SPEC" (2) or "RVSF-SPEC" (3) the live game card isn't displayed properly. 
I suggest that CLA-SPEC and RVSF-SPEC players should be listed in their own team column and their names should be grayed to make it clear that they are spectators.

Screenshot of the problem : 
![bug](https://cloud.githubusercontent.com/assets/5359646/11918797/08658656-a740-11e5-817c-ae06ff621deb.jpg)

**Comment by Sanzouille** [comment]
This is very important considering the upcomming tournament, many games have benched players

**Comment by ScalaWilliam** [comment]
#51 fixes this.
