### ISSUE TITLE
Add country codes & timezones where available

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#54]
This needs a bit more work

**Comment by lucasgautheron** [comment]
Timezones would be a cool bonus, if there is a way to determine them withing a +/- 1 hour error margin. (Doesn't need to be extremely accurate)

**Comment by ScalaWilliam** [comment]
What were the timezones for again?

**Comment by ScalaWilliam** [comment]
Added timezones in f3f9f54d485d889e878a9fb5dbff1847512d7f21, but they aren't available for all IPs.
