### ISSUE TITLE
Game tagging

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#55]

**Comment by ScalaWilliam** [comment]
Tags could be a very generic thing as well.
Some tags manually added, others automatically computed. E.g. manual ones would include tournaments. Automatic ones would include whether it's part of a clanwar, whether it's 2x2, 3x3, which clan it contains, and such. A very generic mechanism in a way, that could then be queried. There are many possibilities here actually.

Game tagging in fact is just another form of enrichment. 
Problem comes when the game enrichment becomes recursive. E.g. we only know that game is part of a clanwar once we've done the clanware computation logic.
In a way this might require us to integrate all the clanwar detection code in Scala and include it as part of the iterator.
But definitely separate this into two:
* Manual tags (easy)
* Automatic tagging and reverse enrichment (e.g. to say this game is part of a clanwar) - it does not have to be preemptive btw, we can compute it on the fly as well.

**Comment by ScalaWilliam** [comment]
@Sanzouille @lucasgautheron what kind of tags do we want then?

**Comment by Sanzouille** [comment]
It's not quite clear for me

**Comment by ScalaWilliam** [comment]
then I'll close since unnecessaryyet

**Comment by lucasgautheron** [comment]
The most obvious use of it would be tournaments ! Then we can extract all the games played for one tournament, make stats for this very tournament, things like this.

**Comment by ScalaWilliam** [comment]
Tags could be stored in an external database.
