### ISSUE TITLE
Tournaments support

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#60]
* Tournaments page : past tournaments, as well as those to come. 
* Tournament page : Website, participating clans ? Then list of games and final result
* Tag tournament games as part of their tournament, see https://github.com/ScalaWilliam/ActionFPS/issues/55
* Include each clan's outstanding tournament performances (e.g. 1st, 2nd and 3rd place) as well as their participation to previous tournaments on their page

(Low priority, requires further discussions)

**Comment by ScalaWilliam** [comment]
Let's move visionary/low priority stuff to the Wiki. e.g. https://github.com/ScalaWilliam/ActionFPS/wiki/Tournaments-Support
