### ISSUE TITLE
Host all image assets somewhere

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#70]

**Comment by ScalaWilliam** [comment]
Plop them all here in this issue then use that link? :)

**Comment by ScalaWilliam** [comment]
http://blog.davidebbo.com/2014/11/using-issues-for-github-pages-screenshots.html

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/12003538/dbd36cea-ab1b-11e5-8f72-f49e784ce30d.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003539/f45936d2-ab1b-11e5-9f50-28e5db485543.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003540/00294678-ab1c-11e5-9660-6e764b07d0df.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003541/0af42866-ab1c-11e5-8a13-c63973cd9d91.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003543/1010d600-ab1c-11e5-8b1e-81af3b09fa4d.png)

![image](https://cloud.githubusercontent.com/assets/2464813/12003544/1c371b10-ab1c-11e5-9629-d15003712653.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003545/21ee2d5a-ab1c-11e5-95d2-fb13a384e478.png)

![image](https://cloud.githubusercontent.com/assets/2464813/12003549/275ee158-ab1c-11e5-9f52-e2c37c32efaa.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003551/2c0955a8-ab1c-11e5-8376-f7a1e6f6f751.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003552/31844aec-ab1c-11e5-83ad-beaab0d637ca.png)

![image](https://cloud.githubusercontent.com/assets/2464813/12003553/375d77d6-ab1c-11e5-9146-7cee96ef81bb.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003555/3c88f898-ab1c-11e5-8310-ebf03959c6d3.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003557/434048bc-ab1c-11e5-85a6-2e287c590161.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003559/4f21e5fa-ab1c-11e5-9d02-007a09ce63f4.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003561/542f6a68-ab1c-11e5-97cc-a12dd5043b1a.png)

![image](https://cloud.githubusercontent.com/assets/2464813/12003562/5857c702-ab1c-11e5-8d59-d69194a669b7.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003563/5d082d1e-ab1c-11e5-8200-c3c68798287f.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003564/62218250-ab1c-11e5-9166-d46241e8b22d.png)

![image](https://cloud.githubusercontent.com/assets/2464813/12003565/66fe6450-ab1c-11e5-894d-e46234d5edb5.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/12003569/859d513c-ab1c-11e5-83f2-ca433f4c6ccd.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003570/88226d52-ab1c-11e5-99e8-508a09d75496.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003571/8a5b336a-ab1c-11e5-831f-3169b62857b7.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003572/936699a4-ab1c-11e5-9384-e6ca00fc4bb9.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003574/95e624ec-ab1c-11e5-9b48-375b40cab31b.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003575/97c7192e-ab1c-11e5-84cb-1e0efb851b53.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003576/9a18d1a4-ab1c-11e5-97f5-39a1d1e517e5.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003577/9cdc2f94-ab1c-11e5-8cff-c8116379078e.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12003578/9f311494-ab1c-11e5-90c2-9064a5b9b493.png)

**Comment by Sanzouille** [comment]
![](http://wiki.cubers.net/images/9/98/Imntperfect2v2.png)

**Comment by lucasgautheron** [comment]
![75thrangerregiment2](https://cloud.githubusercontent.com/assets/5359646/12004100/caeee00e-ab3d-11e5-8b35-9ed661f5b06f.png)

**Comment by lucasgautheron** [comment]
![one](https://cloud.githubusercontent.com/assets/5359646/12004218/d1c7c4a4-ab47-11e5-8084-c9d6d5d7ef2e.png)

**Comment by lucasgautheron** [comment]
![brc](https://cloud.githubusercontent.com/assets/5359646/12004235/a0716ff8-ab48-11e5-8a1c-5714886f1fc6.png)

**Comment by lucasgautheron** [comment]
![fd](https://cloud.githubusercontent.com/assets/5359646/12004238/cb819812-ab48-11e5-8aec-ee7fcea8fef0.png)

**Comment by lucasgautheron** [comment]
![tyd](https://cloud.githubusercontent.com/assets/5359646/12004801/a05504dc-ab78-11e5-85f9-038eb6a4ead9.png)

**Comment by lucasgautheron** [comment]
![u](https://cloud.githubusercontent.com/assets/5359646/12004841/d10c564a-ab7b-11e5-8d41-00e673cc0096.png)

**Comment by lucasgautheron** [comment]
![fra](https://cloud.githubusercontent.com/assets/5359646/12004888/802b28ec-ab7f-11e5-8927-c8b33d9cf74c.png)

**Comment by DaylixX** [comment]
![kh](https://cloud.githubusercontent.com/assets/16243477/12007809/cb6c1352-ac15-11e5-9633-442bb1ba3d2e.png)

**Comment by DaylixX** [comment]
![mys](https://cloud.githubusercontent.com/assets/16243477/12007811/08f26e38-ac16-11e5-8855-e23429e226d8.png)

**Comment by DaylixX** [comment]
![pi](https://cloud.githubusercontent.com/assets/16243477/12007843/9774126e-ac17-11e5-8b05-69ae5cbbbda4.png)

**Comment by DaylixX** [comment]
![frt](https://cloud.githubusercontent.com/assets/16243477/12007891/7e96bc58-ac1a-11e5-909e-eee765f922ac.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/12016400/3d163802-ad42-11e5-829b-57dc96397d02.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/12016782/38687d10-ad47-11e5-9e58-2bfc7d9e473f.png)

**Comment by lucasgautheron** [comment]
mvp.png
![mvp](https://cloud.githubusercontent.com/assets/5359646/12017071/8b8f3f14-ad52-11e5-8825-1b607f03eb11.png)

**Comment by lucasgautheron** [comment]
clanwar.png
![clanwar](https://cloud.githubusercontent.com/assets/5359646/12017079/9f517238-ad52-11e5-89dd-e87ebf06c4e2.png)

**Comment by lucasgautheron** [comment]
![esl](https://cloud.githubusercontent.com/assets/5359646/12019605/7c4a2ef4-ad72-11e5-88fd-c8974a691eff.png)

**Comment by DaylixX** [comment]
![startscreen](https://cloud.githubusercontent.com/assets/16243477/12022846/1c7be248-ad94-11e5-83f0-6ac2faf51a35.jpg)

**Comment by ScalaWilliam** [comment]
wowowowo :+1:

**Comment by DaylixX** [comment]
![icon 32px](https://cloud.githubusercontent.com/assets/16243477/12022947/cb7b73d0-ad94-11e5-9653-86055a2b9209.png)

**Comment by DaylixX** [comment]
![icon 16px](https://cloud.githubusercontent.com/assets/16243477/12022949/d1152584-ad94-11e5-908e-df1db13cb919.png)

**Comment by DaylixX** [comment]
![1920x1080px copie](https://cloud.githubusercontent.com/assets/16243477/12023034/c3086090-ad95-11e5-8081-a280636f103b.jpg)

**Comment by DaylixX** [comment]
![icon 256px](https://cloud.githubusercontent.com/assets/16243477/12023116/82af50a2-ad96-11e5-8f1a-ed866002a231.png)

**Comment by DaylixX** [comment]
![2actionrd256x](https://cloud.githubusercontent.com/assets/16243477/12023545/d0a23c08-ad9a-11e5-9e52-45e8681a61d7.png)

**Comment by DaylixX** [comment]
![2actionrd256x copie](https://cloud.githubusercontent.com/assets/16243477/12023626/85e178b8-ad9b-11e5-8e94-d71cf135feee.png)

**Comment by DaylixX** [comment]
![3actionrd256x](https://cloud.githubusercontent.com/assets/16243477/12023685/2080309e-ad9c-11e5-965c-6a570dcece65.png)

**Comment by DaylixX** [comment]
![3actionrd256x](https://cloud.githubusercontent.com/assets/16243477/12023701/46308ec4-ad9c-11e5-8746-96e58892b115.png)

**Comment by DaylixX** [comment]
![esl](https://cloud.githubusercontent.com/assets/16243477/12023759/02848d28-ad9d-11e5-9e5a-8cb42da9cd12.png)

**Comment by DaylixX** [comment]
![esl2](https://cloud.githubusercontent.com/assets/16243477/12023778/4dbade1e-ad9d-11e5-854f-6d29a90b24a3.png)

**Comment by DaylixX** [comment]
![tyd copie](https://cloud.githubusercontent.com/assets/16243477/12023835/e9c0f71c-ad9d-11e5-9eda-cd16b6c16991.png)

**Comment by DaylixX** [comment]
![iconomfg](https://cloud.githubusercontent.com/assets/16243477/12024083/d68640e6-ada0-11e5-8df1-710acee25e1e.png)

**Comment by DaylixX** [comment]
![sbirds100px](https://cloud.githubusercontent.com/assets/16243477/12025353/4627eeba-adae-11e5-96ff-48f397fa6f76.png)

**Comment by DaylixX** [comment]
![acka](https://cloud.githubusercontent.com/assets/16243477/12076713/7181d0aa-b1b7-11e5-839a-fa47746ff537.png)

**Comment by DaylixX** [comment]
![rc](https://cloud.githubusercontent.com/assets/16243477/12145631/abf8a210-b48f-11e5-8562-3dbcddda19d8.png)

**Comment by DaylixX** [comment]
![rc](https://cloud.githubusercontent.com/assets/16243477/12145853/d3616b38-b490-11e5-9d01-8d49c2bfa666.png)

**Comment by DaylixX** [comment]
![achiemap](https://cloud.githubusercontent.com/assets/16243477/12177590/36d6f52a-b56d-11e5-9da3-c3941c91862f.png)
![butcher](https://cloud.githubusercontent.com/assets/16243477/12177594/37c96616-b56d-11e5-852c-5c27a24edad8.png)
![cube5h](https://cloud.githubusercontent.com/assets/16243477/12177595/3894de72-b56d-11e5-8798-61b18793766c.png)
![cube10h](https://cloud.githubusercontent.com/assets/16243477/12177596/39ceef58-b56d-11e5-8f0d-df421086b9bb.png)
![cube20h](https://cloud.githubusercontent.com/assets/16243477/12177597/3a9655ac-b56d-11e5-8c5e-7949594d5e93.png)
![cube50h](https://cloud.githubusercontent.com/assets/16243477/12177598/3bb677dc-b56d-11e5-82f6-738de302488a.png)
![cube100h](https://cloud.githubusercontent.com/assets/16243477/12177601/3c5ed4c2-b56d-11e5-931a-cd43c3b1162b.png)

**Comment by DaylixX** [comment]
![dday](https://cloud.githubusercontent.com/assets/16243477/12177604/42937992-b56d-11e5-8b3e-5da4438891e4.png)
![flag50](https://cloud.githubusercontent.com/assets/16243477/12177605/4384efd4-b56d-11e5-9957-c9c9f2cd7dfb.png)
![flag100](https://cloud.githubusercontent.com/assets/16243477/12177607/44701306-b56d-11e5-938f-a17690d76f4c.png)
![flag200](https://cloud.githubusercontent.com/assets/16243477/12177608/45587c7c-b56d-11e5-8c09-a41f41fddc82.png)
![flag500](https://cloud.githubusercontent.com/assets/16243477/12177611/460c9ee6-b56d-11e5-87ab-accda07d78a5.png)
![flag1000](https://cloud.githubusercontent.com/assets/16243477/12177613/46dcbf36-b56d-11e5-9849-810b08a047ca.png)
![lucky luck](https://cloud.githubusercontent.com/assets/16243477/12177614/47b9c732-b56d-11e5-92f8-092a647a751f.png)
![maverick](https://cloud.githubusercontent.com/assets/16243477/12177616/48b5d6ee-b56d-11e5-9ba2-0d3303be707e.png)

**Comment by DaylixX** [comment]
![tgame](https://cloud.githubusercontent.com/assets/16243477/12177804/60520f7e-b56e-11e5-9c96-810a980e2fbf.png)

**Comment by DaylixX** [comment]
![tdmlover](https://cloud.githubusercontent.com/assets/16243477/12178298/024e73a6-b571-11e5-92de-102199c9159e.png)

**Comment by lucasgautheron** [comment]
![windows](https://cloud.githubusercontent.com/assets/5359646/12216083/be37fb62-b6d6-11e5-811d-5df9c4ed9fe6.png)

**Comment by lucasgautheron** [comment]
TAA Clan
![clan_picture php](https://cloud.githubusercontent.com/assets/5359646/12576615/441baf08-c415-11e5-9dd3-b5886aadada3.png)

**Comment by lucasgautheron** [comment]
![clanwar](https://cloud.githubusercontent.com/assets/5359646/12597681/7ac32bc8-c486-11e5-9eb4-8be70d5682cc.png)

**Comment by lucasgautheron** [comment]
![ac_douze](https://cloud.githubusercontent.com/assets/5359646/12695151/1beaa7a4-c745-11e5-9577-2cef2722845c.jpg)
![ac_edifice](https://cloud.githubusercontent.com/assets/5359646/12695153/1bed793e-c745-11e5-8c0e-c03d3405de47.jpg)
![ac_elevation](https://cloud.githubusercontent.com/assets/5359646/12695152/1becdf1a-c745-11e5-8564-798f30191533.jpg)
![ac_gothic](https://cloud.githubusercontent.com/assets/5359646/12695155/1bedf4ae-c745-11e5-9d99-fe708e39e050.jpg)
![ac_iceroad](https://cloud.githubusercontent.com/assets/5359646/12695156/1bee8e78-c745-11e5-87c2-eb396b6bb2da.jpg)
![ac_industrial](https://cloud.githubusercontent.com/assets/5359646/12695154/1bed9982-c745-11e5-843f-63653d703313.jpg)
![ac_ingress](https://cloud.githubusercontent.com/assets/5359646/12695157/1bffd958-c745-11e5-83c7-ed9144405076.jpg)
![ac_keller](https://cloud.githubusercontent.com/assets/5359646/12695159/1c02901c-c745-11e5-8ac4-91090f8b0852.jpg)
![ac_lainio](https://cloud.githubusercontent.com/assets/5359646/12695160/1c02a2f0-c745-11e5-80f7-2cb7e21f56fe.jpg)
![ac_mines](https://cloud.githubusercontent.com/assets/5359646/12695158/1c01c696-c745-11e5-9be6-1debec201ecf.jpg)
![ac_outpost](https://cloud.githubusercontent.com/assets/5359646/12695162/1c048d40-c745-11e5-97ac-ebf013d8f968.jpg)
![ac_power](https://cloud.githubusercontent.com/assets/5359646/12695161/1c039192-c745-11e5-820c-2e27a56bb6dd.jpg)
![ac_rattrap](https://cloud.githubusercontent.com/assets/5359646/12695164/1c16133a-c745-11e5-86e2-a550b5661c61.jpg)
![ac_scaffold](https://cloud.githubusercontent.com/assets/5359646/12695165/1c1690e4-c745-11e5-810e-0bede39300cb.jpg)
![ac_shine](https://cloud.githubusercontent.com/assets/5359646/12695166/1c1792f0-c745-11e5-8c8f-8855ae2b44dd.jpg)
![ac_snow](https://cloud.githubusercontent.com/assets/5359646/12695163/1c156b4c-c745-11e5-90f6-99d378b58fd7.jpg)
![ac_stellar](https://cloud.githubusercontent.com/assets/5359646/12695167/1c188c0a-c745-11e5-8b07-40b5e2e2d88c.jpg)
![ac_aqueous](https://cloud.githubusercontent.com/assets/5359646/12695168/1c1a6bec-c745-11e5-8508-06abb1672ef7.jpg)
![ac_arabian](https://cloud.githubusercontent.com/assets/5359646/12695169/1c2aa62e-c745-11e5-8ea1-b702e731ae30.jpg)
![ac_arctic](https://cloud.githubusercontent.com/assets/5359646/12695170/1c2bfbf0-c745-11e5-93cd-e34caf816d82.jpg)
![ac_arid](https://cloud.githubusercontent.com/assets/5359646/12695171/1c2c53d4-c745-11e5-9775-fbe744cea74f.jpg)
![ac_avenue](https://cloud.githubusercontent.com/assets/5359646/12695173/1c2eec3e-c745-11e5-8b47-9ec2581bddcb.jpg)
![ac_cavern](https://cloud.githubusercontent.com/assets/5359646/12695172/1c2e8280-c745-11e5-9a23-2c43ffbfe4e0.jpg)
![ac_complex](https://cloud.githubusercontent.com/assets/5359646/12695174/1c2fdae0-c745-11e5-9fc3-e6c534b350b4.jpg)
![ac_depot](https://cloud.githubusercontent.com/assets/5359646/12695176/1c3f23ba-c745-11e5-9d82-12a438b9e365.jpg)
![ac_desert](https://cloud.githubusercontent.com/assets/5359646/12695175/1c3e42c4-c745-11e5-905f-969068723961.jpg)
![ac_desert2](https://cloud.githubusercontent.com/assets/5359646/12695177/1c421a16-c745-11e5-8997-323d17f281f5.jpg)
![ac_desert3](https://cloud.githubusercontent.com/assets/5359646/12695178/1c42b7dc-c745-11e5-828b-1ea8b1b376f2.jpg)

**Comment by lucasgautheron** [comment]
![cla](https://cloud.githubusercontent.com/assets/5359646/12695180/369c86da-c745-11e5-817f-46d8c4c42376.png)
![rvsf](https://cloud.githubusercontent.com/assets/5359646/12695181/369cda90-c745-11e5-96eb-3f3669f80aed.png)

**Comment by lucasgautheron** [comment]
![skb](https://cloud.githubusercontent.com/assets/5359646/12696491/75343dda-c76c-11e5-8d3f-b95e1a51a71c.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/12760873/99820c6e-c9e0-11e5-832d-00c1b61c2e4c.png)

**Comment by ScalaWilliam** [comment]
![screen shot 2016-02-02 at 20 05 02](https://cloud.githubusercontent.com/assets/2464813/12762693/4e9df7dc-c9e8-11e5-8a2c-704f4af9a25f.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/12814066/25c656a4-cb34-11e5-87a7-dbff30d759c6.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/12814156/cbcd5e62-cb34-11e5-9929-e12fa4170e9c.png)
![image](https://cloud.githubusercontent.com/assets/2464813/12814159/d5a55016-cb34-11e5-9eca-2321924b0b4a.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/12814236/6717aab2-cb35-11e5-822a-c9ad283b27df.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/14408342/412bf156-ff23-11e5-8e64-17a38d7e48d3.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/14592418/dd3d60c4-0550-11e6-9d11-3d826d0fa84b.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/14760732/5a3bae88-097e-11e6-9b40-1e45b56b7e19.png)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/14760741/7128eaca-097e-11e6-89a7-922e790f66d3.png)

**Comment by Sanzouille** [comment]
http://zz.ketar.eu/wp-content/uploads/2016/04/zzlogo1.png

**Comment by Sanzouille** [comment]
![image](http://3i.stylebar.de/wp-content/uploads/2016/05/3i-logo-transparent.png)

**Comment by Sanzouille** [comment]
![name afps](https://cloud.githubusercontent.com/assets/10406781/15368367/af9a3cce-1d2d-11e6-8b65-47747cb06aec.png)

**Comment by Sanzouille** [comment]
![](http://i.imgur.com/pswjBQE.png)

**Comment by Sanzouille** [comment]
![](http://iconizer.net/files/Final_Flags/thumb/64/United-Kingdom-flag.png)

![](http://starkart.ca/files/3214/1564/4678/United-States-Flag-icon.png)

**Comment by ScalaWilliam** [comment]
@Sanzouille last image is huge, would you insert a smaller one?

**Comment by lucasgautheron** [comment]
Also you should extract the biggest square possible from it as AF enforces a 1:1 ratio (affecting highly-non squared logos such as this one pretty bad)

**Comment by ScalaWilliam** [comment]
![image](https://cloud.githubusercontent.com/assets/2464813/19613743/1200ae02-9821-11e6-8c58-bbc24518bc45.png)

**Comment by Paul255** [comment]
![usa](https://cloud.githubusercontent.com/assets/7859727/21722921/d9361e82-d42e-11e6-941f-45d1f6a03fb0.png)

**Comment by DaylixX** [comment]
![backround](https://cloud.githubusercontent.com/assets/16243477/21745316/52a0991e-d529-11e6-8dae-e6048a1d6228.jpg)
![logo](https://cloud.githubusercontent.com/assets/16243477/21745317/52ce445e-d529-11e6-8343-f549218c915e.png)
![action_fr](https://cloud.githubusercontent.com/assets/16243477/21745319/56e4f8d0-d529-11e6-92aa-195a5d0a3732.png)

**Comment by DaylixX** [comment]
[flag.zip](https://github.com/ScalaWilliam/ActionFPS/files/691714/flag.zip)

**Comment by DaylixX** [comment]
[BackGround.zip](https://github.com/ScalaWilliam/ActionFPS/files/691754/BackGround.zip)
Here all Background for the signature on AFPS

**Comment by lucasgautheron** [comment]
![back](https://cloud.githubusercontent.com/assets/5359646/21749443/0ac596a0-d59f-11e6-9a41-7d3b1ccf7bbb.jpg)
![back0](https://cloud.githubusercontent.com/assets/5359646/21749446/0ac5d2c8-d59f-11e6-9f23-074704a1200a.jpg)
![back1](https://cloud.githubusercontent.com/assets/5359646/21749445/0ac5b612-d59f-11e6-9383-05c036ac229f.jpg)
![back2](https://cloud.githubusercontent.com/assets/5359646/21749444/0ac5986c-d59f-11e6-8fb3-0741c59b0cd9.jpg)
![back3](https://cloud.githubusercontent.com/assets/5359646/21749448/0ac8d284-d59f-11e6-93b2-dcd029502b0f.jpg)
![back4](https://cloud.githubusercontent.com/assets/5359646/21749447/0ac5e4a2-d59f-11e6-9dbe-633272d0a920.jpg)
![back5](https://cloud.githubusercontent.com/assets/5359646/21749450/0ad5d18c-d59f-11e6-940b-714ec0c977b0.jpg)
![back6](https://cloud.githubusercontent.com/assets/5359646/21749451/0ad5ccfa-d59f-11e6-9d4e-b4671f8b690c.jpg)
![back7](https://cloud.githubusercontent.com/assets/5359646/21749452/0ad5e8b6-d59f-11e6-9ce7-ff3d1516667b.jpg)
![back9](https://cloud.githubusercontent.com/assets/5359646/21749453/0ad6f148-d59f-11e6-941e-85b918bb4fff.jpg)
![back10](https://cloud.githubusercontent.com/assets/5359646/21749449/0ad5c16a-d59f-11e6-8e31-4ff589f70ce9.jpg)
![back11](https://cloud.githubusercontent.com/assets/5359646/21749454/0ad8b280-d59f-11e6-8eb1-17c94e891745.jpg)
![back12](https://cloud.githubusercontent.com/assets/5359646/21749456/0ae624ba-d59f-11e6-9ecf-eb4fad4e2041.jpg)
![back13](https://cloud.githubusercontent.com/assets/5359646/21749455/0ae5bd40-d59f-11e6-8e6b-6fe4ddacfe03.jpg)
![back14](https://cloud.githubusercontent.com/assets/5359646/21749457/0ae66150-d59f-11e6-9e71-e93abcbf1dab.jpg)
![back15](https://cloud.githubusercontent.com/assets/5359646/21749459/0ae77144-d59f-11e6-8d94-0ce93314c88c.jpg)
![back16](https://cloud.githubusercontent.com/assets/5359646/21749458/0ae77130-d59f-11e6-87c8-a6c0846d4f4b.jpg)
![back17](https://cloud.githubusercontent.com/assets/5359646/21749460/0ae87cba-d59f-11e6-93b9-190283a27976.jpg)
![back18](https://cloud.githubusercontent.com/assets/5359646/21749461/0af5368a-d59f-11e6-87dd-2062107fd9c4.jpg)
![back19](https://cloud.githubusercontent.com/assets/5359646/21749466/0afa26d6-d59f-11e6-97f6-d80d48d80aad.jpg)
![back20](https://cloud.githubusercontent.com/assets/5359646/21749462/0af64840-d59f-11e6-9aac-ea4f6ef0339e.jpg)
![back21](https://cloud.githubusercontent.com/assets/5359646/21749464/0af7588e-d59f-11e6-8788-b90c6e4dfa88.jpg)
![back22](https://cloud.githubusercontent.com/assets/5359646/21749463/0af70618-d59f-11e6-85f4-759da0d6a2f9.jpg)
![back23](https://cloud.githubusercontent.com/assets/5359646/21749465/0af7ac9e-d59f-11e6-8ea7-5753bdcf3a88.jpg)
![back24](https://cloud.githubusercontent.com/assets/5359646/21749467/0b05365c-d59f-11e6-85bc-7261eb5ffbbf.jpg)
![back25](https://cloud.githubusercontent.com/assets/5359646/21749468/0b0612d4-d59f-11e6-9090-dbca3e2db9c5.jpg)
![back26](https://cloud.githubusercontent.com/assets/5359646/21749469/0b0683a4-d59f-11e6-9945-5b11fefc6e76.jpg)
![back27](https://cloud.githubusercontent.com/assets/5359646/21749471/0b07578e-d59f-11e6-8c3e-05ae16d6b508.jpg)
![back28](https://cloud.githubusercontent.com/assets/5359646/21749470/0b06db42-d59f-11e6-8857-28889dbe1e24.jpg)
![back29](https://cloud.githubusercontent.com/assets/5359646/21749472/0b0a8a26-d59f-11e6-87bf-a7333ae678c9.jpg)
![back30](https://cloud.githubusercontent.com/assets/5359646/21749473/0b157314-d59f-11e6-9b7e-50b2fdcd104e.jpg)
![back31](https://cloud.githubusercontent.com/assets/5359646/21749474/0b17ffc6-d59f-11e6-80cd-b6887dddeda8.jpg)

**Comment by lucasgautheron** [comment]
![logo](https://cloud.githubusercontent.com/assets/5359646/21749695/27009eb4-d5a4-11e6-8fd5-b199f1fcd7ea.png)

**Comment by ScalaWilliam** [comment]
![screen shot 2017-01-11 at 20 03 51](https://cloud.githubusercontent.com/assets/2464813/21847871/2f31e204-d839-11e6-9aed-64aa62281442.png)

**Comment by ScalaWilliam** [comment]
From now, let's host image assets against a specific GitHub Issue. This page is getting way too large.

So for anything that needs an Image we create an Issue.

**Comment by lucasgautheron** [comment]
![discord_logo_svg svg](https://cloud.githubusercontent.com/assets/5359646/22435229/8730a392-e71f-11e6-9a10-34f33e6325cf.png)

**Comment by DaylixX** [comment]
![discord](https://cloud.githubusercontent.com/assets/16243477/22436583/fb1c0670-e724-11e6-9d09-3ff60f322eb4.png)

**Comment by lucasgautheron** [comment]
i would have liked the black version better, but ok, thanks

**Comment by DaylixX** [comment]
![discordblack](https://cloud.githubusercontent.com/assets/16243477/22436789/cd7677ea-e725-11e6-88e5-4e5956723196.png)

**Comment by lucasgautheron** [comment]
oh well perfect, thanks

**Comment by Sanzouille** [comment]
![pi_logo_](https://cloud.githubusercontent.com/assets/10406781/25064930/d4810c9c-2205-11e7-8335-5d11707f5b06.jpg)
