### ISSUE TITLE
Game recorded without meeting the requirements

### ISSUE THREAD

**Issue by Sanzouille** [ScalaWilliam/ActionFPS#76]
http://actionfps.com/game/?id=2015-12-25T18:26:03Z
how did this game register?
less than 10 mins played
less than 14 frags average cla

**Comment by Sanzouille** [comment]
http://actionfps.com/game/?id=2016-01-03T19:36:49Z

same here

**Comment by lucasgautheron** [comment]
For instance : http://actionfps.com/game/?id=2016-01-18T16:55:14Z
