### ISSUE TITLE
Player left AFTER intermission and doesn't appear on game card

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#77]
The games : 
http://actionfps.com/game/?id=2015-12-25T18:51:44Z
http://actionfps.com/game/?id=2015-12-25T19:07:29Z

In game screenshot : http://imgur.com/a/7QV7K

As you can see the team score is correct, however the player (p00p|aaa) is missing

**Comment by lucasgautheron** [comment]
What is the ready tag for ? This bug doesn't seem fixed at the moment

**Comment by ScalaWilliam** [comment]
ready means ready to be worked on ;)

**Comment by lucasgautheron** [comment]
http://imgur.com/D1PTZ3z
http://actionfps.com/game/?id=2016-01-14T18:37:08Z

**Comment by lucasgautheron** [comment]
Million isn't sure he hadn't left. Issue not confirmed, hence closed
