### ISSUE TITLE
Games not appearing

### ISSUE THREAD

**Issue by Sanzouille** [ScalaWilliam/ActionFPS#84]
http://actionfps.com/game/?id=2015-12-26T21:41:28Z

These guys played two other games, it should have been a 3 rounds clanwar. However 2 games are NOT on actionfps. 

Nothing special happened during these two games.

This is quite big, might be top priority

**Comment by Sanzouille** [comment]
Games were played on NY 33333, can't check the logs on my side

**Comment by ScalaWilliam** [comment]
If we see this again, open a new ticket.
