### ISSUE TITLE
Clan tags pattern

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#87]
How to deal with clan tags which are worn this way ? :

ESL|Zodiac
Marlboro|ESL 

As far as i understand the current system cannot deal with them.

**Comment by ScalaWilliam** [comment]
Add tag ESL|* and then *|ESL to the spreadsheet. There are two columns next to each other ;)

**Comment by lucasgautheron** [comment]
Thanks
