### ISSUE TITLE
!inter only works on aura servers

### ISSUE THREAD

**Issue by lucasgautheron** [ScalaWilliam/ActionFPS#91]
not really a bug as it seems intended in the code, but it should work everywhere

https://github.com/ScalaWilliam/ActionFPS/blob/c655e5b48ce809badd16fb0b306047fdb9252196/inter-parser/src/main/scala/inter/package.scala#L24

**Comment by ScalaWilliam** [comment]
Parsing was easier - this can definitely be sorted though.

**Comment by lucasgautheron** [comment]
excellent. I will try to find out how to make sure valid-servers values are valid
