### ISSUE TITLE
Capture master achievment

### ISSUE THREAD

**Issue by Sanzouille** [ScalaWilliam/ActionFPS#96]
http://actionfps.com/game/?id=2016-01-01T13:58:24Z
this game
should have give me depot
in capture master
ctf @ ac_depot 3/3 2/3
didnt work

**Comment by lucasgautheron** [comment]
hint? he got 4 flags and the achievement shows 4 times

**Comment by lucasgautheron** [comment]
ActionFPS seemsto be missing maps in comparison to woop;ac : 
http://actionfps.com/player/?id=ven
http://woop.ac/player/ven50/

**Comment by ScalaWilliam** [comment]
Isn't that a registration date thing @lucasgautheron

**Comment by lucasgautheron** [comment]
Ah, indeed, lots of missing games on actionfps (40/110)

**Comment by Sanzouille** [comment]
Website stated that i needed 1 round CLA depot, did it twice nothing happened. Did a deport RVSF yesterday and got the achievment.
