### ISSUE TITLE
games not found on player page

### ISSUE THREAD

**Issue by Sanzouille** [ScalaWilliam/ActionFPS#97]
http://actionfps.com/player/?id=sanzo
click last two achievments earned
http://actionfps.com/game/?id=2016-01-01T14:44:26Z

'game not found'

**Comment by lucasgautheron** [comment]
These games are also missing on actionfps.com :
http://actionfps.com:81/game/?id=2016-01-01T15:16:37Z
http://actionfps.com:81/game/?id=2016-01-01T14:44:26Z
http://actionfps.com:81/game/?id=2016-01-01T14:28:19Z
I lost 18 games among 416 games on my profile

**Comment by ScalaWilliam** [comment]
Closed by 9a686ca3251ed24ae18be2517ab17bcd5569308b

**Comment by lucasgautheron** [comment]
<3
